
Insert into FT_T_FLDF(FLD_ID,LAST_CHG_TMS,LAST_CHG_USR_ID,DDL_NME,FLD_USED_BY_TYP,FLD_NME,FLD_DATA_CL_ID)
SELECT 'CNT10017',TO_DATE('2024-06-03 21:40:20','YYYY-MM-DD HH24:MI:SS'),'AUTO','CNTRCT_CRTE_OPTN','T','Contract Rate Option','BETEXT'FROM DUAL 
WHERE NOT EXISTS (SELECT 'X' FROM FT_T_FLDF WHERE FLD_ID = 'CNT10017');


Insert into FT_T_CLDF(TBL_ID,LAST_CHG_TMS,LAST_CHG_USR_ID,COL_NME,FLD_ID,COL_REQ_IND,DDL_DATA_TYP,COL_SQ_NUM,LOGL_NME,COL_DESC,DDL_BASE_DATA_TYP,DDL_DATA_LEN,DDL_DATA_PREC_NUM,DDL_DATA_SCALE_NUM,DDL_DATA_DFLT_TXT,COL_VIEW_NME,INFO_TYP_NME,DSPY_CAPTION_TXT)
select 'CNT1',TO_DATE('2024-06-03 21:40:20','YYYY-MM-DD HH24:MI:SS'),'AUTO','CNTRCT_CRTE_OPTN','CNT10017','N','VARCHAR(255)',18,'Contract Rate Option','Contract Rate Option','VARCHAR',255,0,0,null,'CNTRCT_CRTE_OPTN','STANDARD_BE_TEXT','Contract Rate Option'
WHERE NOT EXISTS (SELECT 'X' FROM FT_T_CLDF WHERE FLD_ID = 'CNT10017');



Insert into FT_T_XELM(SEGMENT_ID,LAST_CHG_TMS,LAST_CHG_USR_ID,TBL_ID,ELEMENT_NME,ELEMENT_XML_TAG,COL_NME)
select 6778851,TO_DATE('2024-06-03 21:40:34','YYYY-MM-DD HH24:MI:SS'),'AUTO','CNT1','Contract Rate Option','CNTRCTCRTEOPTN','CNTRCT_CRTE_OPTN'
where not exists (select * from FT_T_XELM where segment_id='6778851'
and LAST_CHG_USR_ID='AUTO'
and TBL_ID='CNT1'
and ELEMENT_NME='Contract Rate Option'
and ELEMENT_XML_TAG='CNTRCTCRTEOPTN'
and COL_NME='CNTRCT_CRTE_OPTN');