DELETE FROM FT_T_TBDF WHERE TBL_ID in ( 'MSC1','CNT1','NDF1','NPF1','NPP1','PRA1','UDF1','UDR1' );

DELETE FROM FT_T_XSTO WHERE TBL_ID in ( 'MSC1','CNT1','NDF1','NPF1','NPP1','PRA1','UDF1','UDR1' );

DELETE FROM FT_T_XSEG WHERE SEGMENT_DESC in ( 'MSC1','CNT1','NDF1','NPF1','NPP1','PRA1','UDF1','UDR1' );

DELETE FROM FT_T_CLMI WHERE TRGT_TBL_ID in ('MSC1', 'CNT1','NDF1','NPF1','NPP1','PRA1','UDF1','UDR1' );

DELETE FROM FT_T_ETDF WHERE TBL_SYNM_ID in ('MSC1', 'CNT1','NDF1','NPF1','NPP1','PRA1','UDF1','UDR1' );


