insert
	into
	ft_t_idcs (id_ctxt_sq_key_id,
	plne_org_id,
	prodln_id,
	org_id,
	acct_org_id,
	bk_id,
	acct_id,
	iss_typ_grp_oid,
	id_ctxt_typ,
	id_ctxt_sq_num,
	tbl_typ,
	last_chg_tms,
	last_chg_usr_id,
	global_uniq_ind,
	id_ctxt_purp_typ,
	acct_oid,
	plne_oid,
	id_ctxt_desc,
	iss_typ)
select
	'NVNIDCS034' as id_ctxt_sq_key_id,
	null as plne_org_id,
	null as prodln_id,
	null as org_id,
	null as acct_org_id,
	null as bk_id,
	null as acct_id,
	null as iss_typ_grp_oid,
	'MRTCRID' as id_ctxt_typ,
	1 as id_ctxt_sq_num,
	'FIID' as tbl_typ,
	sysdate() as last_chg_tms,
	'NUVEEN:CSTM' as last_chg_usr_id,
	'S' as global_uniq_ind,
	null as id_ctxt_purp_typ,
	null as acct_oid,
	null as plne_oid,
	null as id_ctxt_desc,
	null as iss_typ on
	conflict (tbl_typ,
	id_ctxt_typ,
	coalesce(org_id,
	'=NULL='::character varying),
	coalesce(plne_oid,
	'=NULL='::character varying),
	coalesce(acct_oid,
	'=NULL='::character varying),
	coalesce(iss_typ_grp_oid,
	'=NULL='::character varying),
	coalesce(iss_typ,
	'=NULL='::character varying))
where
	(id_ctxt_typ = 'MRTCRID'
		and tbl_typ = 'FIID') do
update
set
	id_ctxt_sq_key_id = EXCLUDED.id_ctxt_sq_key_id,
	plne_org_id = EXCLUDED.plne_org_id,
	prodln_id = EXCLUDED.prodln_id,
	org_id = EXCLUDED.org_id,
	acct_org_id = EXCLUDED.acct_org_id,
	bk_id = EXCLUDED.bk_id,
	acct_id = EXCLUDED.acct_id,
	iss_typ_grp_oid = EXCLUDED.iss_typ_grp_oid,
	id_ctxt_typ = EXCLUDED.id_ctxt_typ,
	id_ctxt_sq_num = EXCLUDED.id_ctxt_sq_num,
	tbl_typ = EXCLUDED.tbl_typ,
	last_chg_tms = EXCLUDED.last_chg_tms,
	last_chg_usr_id = EXCLUDED.last_chg_usr_id,
	global_uniq_ind = EXCLUDED.global_uniq_ind,
	id_ctxt_purp_typ = EXCLUDED.id_ctxt_purp_typ,
	acct_oid = EXCLUDED.acct_oid,
	plne_oid = EXCLUDED.plne_oid,
	id_ctxt_desc = EXCLUDED.id_ctxt_desc,
	iss_typ = EXCLUDED.iss_typ;