INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc) SELECT 'EMCLASS','EMCLASS',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','EM Classification','Emerging Markets Group Classification' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'EMCLASS' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc) SELECT 'REAASSCLS','REAASSCLS',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','REA Asset Class','Asset Class used in 801, 270, 275 reprots for REA account' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'REAASSCLS' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc) SELECT 'REAASSSUB','REAASSSUB',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','REA Asset Sub Class','Asset Sub Class used in 801, 270, 275 reprots for REA account' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'REAASSSUB' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc) SELECT 'REAINSTTYP','REAINSTTYP',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','REA Instrument Type','Instrument Type used in 801, 270, 275 reprots for REA account' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'REAINSTTYP' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc) SELECT 'BARCPURPCL','BARCPURPCL',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','Barclays Purpose Class','Barclays Index methodology assignment of the bonds purpose. Certain clients use this data for reporting and compliance testing' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'BARCPURPCL' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc) SELECT 'PRCASSCLS','PRCASSCLS',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','Pricing Asset Class','Pricing Asset Class' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'PRCASSCLS' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc) SELECT 'SVTASSCLS5','SVTASSCLS5',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','SVT Asset Class Lvl 5','SVT Asset Class Lvl 5' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'SVTASSCLS5' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc) SELECT 'LAASSSUBCL','LAASSSUBCL',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','LA Asset Subclass ','LA Asset Subclass ' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'LAASSSUBCL' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc) SELECT 'LAASSCLS','LAASSCLS',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','LA Asset Class ','LA Asset Class ' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'LAASSCLS' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc) SELECT 'TFICLASS1','TFICLASS1',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','TFI Class 1','TFI Class 1' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'TFICLASS1' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc) SELECT 'TFICLASS2','TFICLASS2',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','TFI Class 2','TFI Class 2' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'TFICLASS2' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc) SELECT 'TFICLASS3','TFICLASS3',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','TFI Class 3','TFI Class 3' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'TFICLASS3' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc) SELECT 'TFICLASS4','TFICLASS4',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','TFI Class 4','TFI Class 4' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'TFICLASS4' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc) SELECT 'HYBSRCGICS','HYBSRCGICS',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','Hybrid Source – GICS ','Hybrid Source – GICS ' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'HYBSRCGICS' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc) SELECT 'TIAAINDUS','TIAAINDUS',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','Industry Diversification (TIAA)','internally created two level industry diversification list' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'TIAAINDUS' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc) SELECT 'NWQBARC2','NWQBARC2',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','NWQ Barclays 2','NWQ Barclays 2' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'NWQBARC2' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc) SELECT 'NVCOMMDTY','NVCOMMDTY',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','Nuveen Commodity','Nuveen Commodity' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'NVCOMMDTY' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc) SELECT 'NVCOMMGRP','NVCOMMGRP',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','Nuveen Commodity Group','Nuveen Commodity Group' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'NVCOMMGRP' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc) SELECT 'RAASSTOW','RAASSTOW',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','RA ASSET CLASS','RA ASSET CLASS (Old Name: GIF Asset Class (Global Infrastructure))' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'RAASSTOW' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc) SELECT 'GIFCUSTSEC','GIFCUSTSEC',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','RA INDUSTRY','RA INDUSTRY (Old Name: GIF Custom Sector (Global Infrastructure))' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'GIFCUSTSEC' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc) SELECT 'LAASTOVRDE','LAASTOVRDE',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','LA Asset Class Override','LA Asset Class Override' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'LAASTOVRDE' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc) SELECT 'NAMWCLUST','NAMWCLUST',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','NAM West Cluster','NAM West Cluster' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'NAMWCLUST' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc) SELECT 'NAMWGICSEC','NAMWGICSEC',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','NAM West Custom GIC Sector','NAM West Custom GIC Sector' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'NAMWGICSEC' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc) SELECT 'NAMWTHEME','NAMWTHEME',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','NAM West Theme','NAM West Theme' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'NAMWTHEME' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc) SELECT 'NWQMKTSECT','NWQMKTSECT',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','NWQ Market Sector','NWQ Market Sector' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'NWQMKTSECT' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc) SELECT 'NWQMERPFD','NWQMERPFD',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','NWQ Merrill Preferred Sector','NWQ Merrill Preferred Sector' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'NWQMERPFD' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc) SELECT 'NWQMERSEC','NWQMERSEC',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','NWQ Merrill Sector','NWQ Merrill Sector' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'NWQMERSEC' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc) SELECT 'NWQMERSUB','NWQMERSUB',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','NWQ Merrill Sub Sector','NWQ Merrill Sub Sector' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'NWQMERSUB' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc) SELECT 'GIFASETCLS','GIFASETCLS',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','RA TYPE','RA TYPE (Old Name: RA ASSET TYPE/Real Assets Asset OW)' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'GIFASETCLS' );

--INCS for S&P and Moody's
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc,data_src_id)    SELECT 'NVNLRDSP','NVNLRDSP',sysdate(),sysdate(),'NUVEEN:CSTM','S&P','S&P',''     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'NVNLRDSP' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc,data_src_id)    SELECT 'NVNLRDMDY','NVNLRDMDY',sysdate(),sysdate(),'NUVEEN:CSTM','Moody Corp','Moody Corp',''     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'NVNLRDMDY' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc,data_src_id)    SELECT 'NVNLRDMDCL','NVNLRDMDCL',sysdate(),sysdate(),'NUVEEN:CSTM','Moodys CLO Indenture SIC Code','Moodys CLO Indenture SIC Code',''     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'NVNLRDMDCL' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc,data_src_id)    SELECT 'NVNLRDGICS','NVNLRDGICS',sysdate(),sysdate(),'NUVEEN:CSTM','S&P Cap IQ GICS','S&P Cap IQ GICS',''     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'NVNLRDGICS' );


--INCS Domain Inserts

INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc,data_src_id) SELECT 'EGLSECTYP','EGLSECTYP',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','Eagle Security Type','Eagle Security Type','NUVEEN' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'EGLSECTYP' );

INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc,data_src_id) SELECT 'EGLINVTYP','EGLINVTYP',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','Eagle Investment Type','Eagle Investment Type','NUVEEN' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'EGLINVTYP' );



--added for BBG custom code changes

INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc,data_src_id) SELECT 'BICSLVL1','BICSLVL1',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','BICS Level 1 Sector Code','BICS Level 1 Sector Code','BICS Level 1 Sector Code' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'BICSLVL1' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc,data_src_id) SELECT 'BICSLVL2','BICSLVL2',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','BICS Level 2 Industry Group Code','BICS Level 2 Industry Group Code','BICS Level 2 Industry Group Code' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'BICSLVL2' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc,data_src_id) SELECT 'BICSLVL3','BICSLVL3',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','BICS Level 3 Industry Code','BICS Level 3 Industry Code','BICS Level 3 Industry Code' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'BICSLVL3' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc,data_src_id) SELECT 'BICSLVL4','BICSLVL4',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','BICS Level 4 Sub Industry Code','BICS Level 4 Sub Industry Code','BICS Level 4 Sub Industry Code' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'BICSLVL4' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc,data_src_id) SELECT 'BICSLVL5','BICSLVL5',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','BICS Level 5 Segment Code','BICS Level 5 Segment Code','BICS Level 5 Segment Code' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'BICSLVL5' );

-- Merrill Lynch inserts
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc) SELECT 'MERRILL1','MERRILL1',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','Nuveen ML 1','Nuveen ML 1' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'MERRILL1' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc) SELECT 'MERRILL2','MERRILL2',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','Nuveen ML 2','Nuveen ML 2' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'MERRILL2' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc) SELECT 'MERRILL3','MERRILL3',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','Nuveen ML 3','Nuveen ML 3' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'MERRILL3' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc) SELECT 'MERRILL4','MERRILL4',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','Nuveen ML 4','Nuveen ML 4' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'MERRILL4' );

--INCS for Eagle derivations
INSERT INTO ft_t_incs
(indus_cl_set_id, cl_set_purp_typ, start_tms, end_tms, last_chg_tms, last_chg_usr_id, cross_ref_id, cl_set_nme, cl_set_desc, gu_id, gu_typ, gu_cnt, clsf_set_mnem, clsf_tenor_mnem, clsf_set_curr_cde, clsf_set_tbl_typ, data_stat_typ, data_src_id, inst_mnem, gunt_oid)
SELECT 'EGLOANSTYP', NULL, SYSDATE(), NULL, SYSDATE(), 'NUVEEN:CSTM', NULL, 'Eagle Loan Sec Type', 'Eagle Loan Sec Type', NULL, NULL, NULL, 'EGLOANSTYP', NULL, NULL, NULL, NULL, 'NUVEEN', NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'EGLOANSTYP' );

INSERT INTO ft_t_incs (indus_cl_set_id, cl_set_purp_typ, start_tms, end_tms, last_chg_tms, last_chg_usr_id, cross_ref_id, cl_set_nme, cl_set_desc, gu_id, gu_typ, gu_cnt, clsf_set_mnem, clsf_tenor_mnem, clsf_set_curr_cde, clsf_set_tbl_typ, data_stat_typ, data_src_id, inst_mnem, gunt_oid) SELECT 'EGBBSECTYP', NULL, SYSDATE(), NULL, SYSDATE(), 'NUVEEN:CSTM', NULL, 'Eagle Bloomberg Sec Type', 'Eagle Bloomberg Sec Type', NULL, NULL, NULL, 'EGBBSECTYP', NULL, NULL, NULL, NULL, 'NUVEEN', NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'EGBBSECTYP' );

INSERT INTO FT_T_INCS
(indus_cl_set_id, cl_set_purp_typ, start_tms, end_tms, last_chg_tms, last_chg_usr_id, cross_ref_id, cl_set_nme, cl_set_desc, gu_id, gu_typ, gu_cnt, clsf_set_mnem, clsf_tenor_mnem, clsf_set_curr_cde, clsf_set_tbl_typ, data_stat_typ, data_src_id, inst_mnem, gunt_oid)
SELECT 'EGLPRFCLAS', NULL, SYSDATE(), NULL, SYSDATE(), 'NUVEEN:CSTM', NULL, 'Eagle Preffered Class', 'Eagle Preffered Class', NULL, NULL, NULL, 'EGLPRFCLAS', NULL, NULL, NULL, NULL, 'NUVEEN', NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'EGLPRFCLAS' );

-- PRSECTYP
INSERT INTO FT_T_INCS
(indus_cl_set_id, cl_set_purp_typ, start_tms, end_tms, last_chg_tms, last_chg_usr_id, cross_ref_id, cl_set_nme, cl_set_desc, gu_id, gu_typ, gu_cnt, clsf_set_mnem, clsf_tenor_mnem, clsf_set_curr_cde, clsf_set_tbl_typ, data_stat_typ, data_src_id, inst_mnem, gunt_oid)
SELECT 'PRSECTYP', NULL, SYSDATE(), NULL, SYSDATE(), 'NUVEEN:CSTM', NULL, 'Eagle Processed Security Type', 'Eagle Processed Security Type', NULL, NULL, NULL, 'PRSECTYP', NULL, NULL, NULL, NULL, 'NUVEEN', NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'PRSECTYP' );

--Credit Scope

INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc,data_src_id)    SELECT 'NUVSECCDE','NUVSECCDE',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','Nuveen Security Code','Nuveen Security Code',''     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'NUVSECCDE' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc,data_src_id)    SELECT 'NUVSECNUM','NUVSECNUM',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','Nuveen Muni Sector Code','Nuveen Muni Sector Code',''     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'NUVSECNUM' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc,data_src_id)    SELECT 'MRTSECNUM','MRTSECNUM',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','Nuveen Merritt Sector Code','Nuveen Merritt Sector Code',''     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'MRTSECNUM' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc,data_src_id)    SELECT 'NVNDBSTR','NVNDBSTR',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','Nuveen Debt Structure','Nuveen Debt Structure',''     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'NVNDBSTR' );
INSERT INTO ft_t_incs (indus_cl_set_id, clsf_set_mnem, start_tms, last_chg_tms, last_chg_usr_id, cl_set_nme, cl_set_desc,data_src_id)    SELECT 'NVNISSTY','NVNISSTY',SYSDATE(),SYSDATE(),'NUVEEN:CSTM','Nuveen Issue Type','Nuveen Issue Type',''     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incs WHERE indus_cl_set_id = 'NVNISSTY' );
