
INSERT INTO  ft_m_jbcf
(jbcf_oid, job_name, job_desc, job_typ, job_run_day, job_start_time, job_end_time, job_run_freq, exp_run_dur, last_chg_tms, start_tms, end_tms, in_query, pub_query, val_query, result_column, to_mail, info_mail, task_start_check, multi_check, holiday_check, range_check)
select '=000351804', 'Nuveen_LevFin_ISGP_Refresh', 'ISGP Refresh Job', 'Fileload', 'TUE,WED,THU,FRI,SAT', '01:05', '01:10', '1', 5, '2023-11-08 01:03:02.000', '2023-11-08 01:03:02.000', NULL, 'select  max(job_id)  as job_id , case when count(*) > 0 then ''Nuveen_LevFin_ISGP_Refresh Completed Successfull!! OK'' else ''Nuveen_LevFin_ISGP_Refresh not Completed Successfull!! KO'' end as result  from ft_t_jblg where job_config_txt = ''LevFin ISGP Refresh Job''  and job_start_tms::date >= sysdate()::date', NULL, NULL, 'RESULT', 'gsodmonitoring@thegoldensource.com,nuveenondemand@thegoldensource.com,yogesh.raut@nuveen.com,yraut@thegoldensource.com', 'ODAlerts@thegoldensource.com,nuveenondemand@thegoldensource.com,yogesh.raut@nuveen.com,yraut@thegoldensource.com', 'N', 'N', 'N', 'N' 
from dual where not exists (select 'x' from ft_m_jbcf where job_name = 'Nuveen_LevFin_ISGP_Refresh');

INSERT INTO  ft_m_jbcf
(jbcf_oid, job_name, job_desc, job_typ, job_run_day, job_start_time, job_end_time, job_run_freq, exp_run_dur, last_chg_tms, start_tms, end_tms, in_query, pub_query, val_query, result_column, to_mail, info_mail, task_start_check, multi_check, holiday_check, range_check)
select '=000351802', 'Nuveen_LevFin_WSO_Load_Process', 'WSO_SMF_Asset*.txt DataLoad', 'Fileload', 'TUE,WED,THU,FRI,SAT', '01:31', '02:31', '1', 60, '2023-11-07 23:49:01.000', '2023-11-07 23:49:01.000', NULL, 'select max(job_id) as job_id , case when count(*) > 0 then  ''WSO Dataload Parent Job is Loaded OK'' else ''WSO Dataload Parent Job is not yet Loaded KO''  end as result from ft_t_jblg where job_id in (select max(prnt_job_id) from  ft_t_jblg where  job_input_txt ~* ''WSO_SMF_Asset.*\.txt'' and job_config_txt is null  and job_start_tms::date >= sysdate()::date ) and job_stat_typ  = ''CLOSED'' and job_config_txt =''WSO Dataload Parent Job''', NULL, NULL, 'RESULT', 'gsodmonitoring@thegoldensource.com,nuveenondemand@thegoldensource.com,yogesh.raut@nuveen.com,yraut@thegoldensource.com', 'ODAlerts@thegoldensource.com,nuveenondemand@thegoldensource.com,yogesh.raut@nuveen.com,yraut@thegoldensource.com', 'N', 'N', 'N', 'N' 
from dual where not exists (select 'x' from ft_m_jbcf where job_name = 'Nuveen_LevFin_WSO_Load_Process');

INSERT INTO  ft_m_jbcf
(jbcf_oid, job_name, job_desc, job_typ, job_run_day, job_start_time, job_end_time, job_run_freq, exp_run_dur, last_chg_tms, start_tms, end_tms, in_query, pub_query, val_query, result_column, to_mail, info_mail, task_start_check, multi_check, holiday_check, range_check)
select '=000351801', 'Nuveen_LevFin_LRD_Load_Process', 'LRD-*.json DataLoad', 'Fileload', 'TUE,WED,HU,FRI,SAT', '02:31', '03:31', '1', 30, '2023-11-07 09:08:51.000', '2023-11-07 09:08:51.000', NULL, 'select max(job_id) as job_id , case when count(*) > 0 then  ''Markit LRD Dataload Parent Job is Loaded OK'' else ''Markit LRD Dataload Parent Job is not yet Loaded KO''  end as result from ft_t_jblg where job_id in (select max(prnt_job_id) from  ft_t_jblg where  job_input_txt ~* ''LRD-*-.*\.json'' and job_config_txt is null  and job_start_tms::date >= sysdate()::date ) and job_stat_typ  = ''CLOSED'' and job_config_txt =''Markit LRD Dataload Parent Job''', NULL, NULL, 'RESULT', 'gsodmonitoring@thegoldensource.com,nuveenondemand@thegoldensource.com,yogesh.raut@nuveen.com,yraut@thegoldensource.com', 'ODAlerts@thegoldensource.com,nuveenondemand@thegoldensource.com,yogesh.raut@nuveen.com,yraut@thegoldensource.com', 'N', 'N', 'N', 'N' 
 from dual where not exists (select 'x' from ft_m_jbcf where job_name = 'Nuveen_LevFin_LRD_Load_Process');

INSERT INTO  ft_m_jbcf
(jbcf_oid, job_name, job_desc, job_typ, job_run_day, job_start_time, job_end_time, job_run_freq, exp_run_dur, last_chg_tms, start_tms, end_tms, in_query, pub_query, val_query, result_column, to_mail, info_mail, task_start_check, multi_check, holiday_check, range_check)
select '=000351803', 'Nuveen_LevFin_Eagle_Load_Process', 'EDI_GS_*.txt DataLoad', 'Fileload', 'TUE,WED,THU,FRI,SAT', '03:00', '03:31', '1', 30, '2023-11-07 23:52:01.000', '2023-11-07 23:52:01.000', NULL, 'select max(job_id)  as job_id , case when count(*) > 0 then  ''Eagle EDI Dataload Parent Job is Loaded OK'' else ''Eagle EDI Dataload Parent Job is not yet Loaded KO''  end as result from ft_t_jblg where job_id in (select max(prnt_job_id) from  ft_t_jblg where  job_input_txt ~* ''EDI_GS_.*\.txt'' and job_config_txt is null  and job_start_tms::date >= sysdate()::date ) and job_stat_typ  = ''CLOSED'' and job_config_txt =''Eagle EDI Dataload Parent Job''', NULL, NULL, 'RESULT', 'gsodmonitoring@thegoldensource.com,nuveenondemand@thegoldensource.com,yogesh.raut@nuveen.com,yraut@thegoldensource.com', 'ODAlerts@thegoldensource.com,nuveenondemand@thegoldensource.com,yogesh.raut@nuveen.com,yraut@thegoldensource.com', 'N', 'N', 'N', 'N' 
from dual where not exists (select 'x' from ft_m_jbcf where job_name = 'Nuveen_LevFin_Eagle_Load_Process');

INSERT INTO  ft_m_jbcf
(jbcf_oid, job_name, job_desc, job_typ, job_run_day, job_start_time, job_end_time, job_run_freq, exp_run_dur, last_chg_tms, start_tms, end_tms, in_query, pub_query, val_query, result_column, to_mail, info_mail, task_start_check, multi_check, holiday_check, range_check)
select '=000351805', 'Nuveen_LevFin_BBPerSec_Load_Process', 'BB Per-Security Request', 'Fileload', 'TUE,WED,THU,FRI,SAT', '03:00', '03:31', '1', 30, '2023-11-08 04:21:55.000', '2023-11-08 04:21:55.000', NULL, 'select  max(job_id)  as job_id , case when count(*) > 0 then ''LevFin - Bloomberg Per Security Job Completed Successfull!! OK'' else ''LevFin - Bloomberg Per Security Job not Completed Successfull!! KO'' end as result  from ft_t_jblg where prnt_job_id in (select job_id from ft_t_jblg where  job_config_txt = ''LevFin - Bloomberg Per Security Job'' and job_stat_typ  = ''CLOSED'' and job_start_tms::date >= sysdate()::date)', NULL, NULL, 'RESULT', 'gsodmonitoring@thegoldensource.com,nuveenondemand@thegoldensource.com,yogesh.raut@nuveen.com,yraut@thegoldensource.com', 'ODAlerts@thegoldensource.com,nuveenondemand@thegoldensource.com,yogesh.raut@nuveen.com,yraut@thegoldensource.com', 'N', 'N', 'N', 'N' 
from dual where not exists (select 'x' from ft_m_jbcf where job_name = 'Nuveen_LevFin_BBPerSec_Load_Process');

INSERT INTO  ft_m_jbcf
(jbcf_oid, job_name, job_desc, job_typ, job_run_day, job_start_time, job_end_time, job_run_freq, exp_run_dur, last_chg_tms, start_tms, end_tms, in_query, pub_query, val_query, result_column, to_mail, info_mail, task_start_check, multi_check, holiday_check, range_check)
select '=000363150', 'Nuveen_LevFin_EOD_Issuer_Publish_Process', 'EOD Issuers Publish', 'Publishing', 'TUE,WED,THU,FRI,SAT', '03:15', '03:45', '1', 15, '2023-11-08 06:58:18.000', '2023-11-08 06:58:18.000', NULL, 'select  max(job_id)  as job_id , case when count(*) > 0 then ''LevFin EOD Issuer Publish!! OK'' else ''LevFin EOD Issuer Publish not Successful!! KO'' end as result from ft_t_jblg where job_id in (select job_id from ft_t_jblg where  job_config_txt = ''LevFin EOD Issuer Publish'' and job_stat_typ  = ''CLOSED'' and job_start_tms::date >= sysdate()::date)', NULL, NULL, 'RESULT', 'gsodmonitoring@thegoldensource.com,nuveenondemand@thegoldensource.com,yogesh.raut@nuveen.com,yraut@thegoldensource.com', 'ODAlerts@thegoldensource.com,nuveenondemand@thegoldensource.com,yogesh.raut@nuveen.com,yraut@thegoldensource.com', 'N', 'N', 'N', 'N' 
from dual where not exists (select 'x' from ft_m_jbcf where job_name = 'Nuveen_LevFin_EOD_Issuer_Publish_Process');

INSERT INTO  ft_m_jbcf
(jbcf_oid, job_name, job_desc, job_typ, job_run_day, job_start_time, job_end_time, job_run_freq, exp_run_dur, last_chg_tms, start_tms, end_tms, in_query, pub_query, val_query, result_column, to_mail, info_mail, task_start_check, multi_check, holiday_check, range_check)
select '=000351806', 'Nuveen_LevFin_EOD_Publish_Process', 'EOD Securities Publish', 'Publishing', 'TUE,WED,THU,FRI,SAT', '03:15', '03:45', '1', 15, '2023-11-08 06:58:18.000', '2023-11-08 06:58:18.000', NULL, 'select  max(job_id)  as job_id , case when count(*) > 0 then ''LevFin EOD Securities Publish!! OK'' else ''LevFin EOD Securities Publish not Successful!! KO'' end as result from ft_t_jblg where job_id in (select job_id from ft_t_jblg where  job_config_txt = ''LevFin EOD Securities Publish'' and job_stat_typ  = ''CLOSED'' and job_start_tms::date >= sysdate()::date)', NULL, NULL, 'RESULT', 'gsodmonitoring@thegoldensource.com,nuveenondemand@thegoldensource.com,yogesh.raut@nuveen.com,yraut@thegoldensource.com', 'ODAlerts@thegoldensource.com,nuveenondemand@thegoldensource.com,yogesh.raut@nuveen.com,yraut@thegoldensource.com', 'N', 'N', 'N', 'N' 
from dual where not exists (select 'x' from ft_m_jbcf where job_name = 'Nuveen_LevFin_EOD_Publish_Process');


-- Property Master Merge 24042024
insert into ft_m_jbcf (jbcf_oid,job_name,job_desc,job_typ,job_run_day,job_start_time,job_end_time,job_run_freq,exp_run_dur,last_chg_tms,start_tms,end_tms,in_query,pub_query,val_query,result_column,to_mail,info_mail,task_start_check,multi_check,holiday_check,range_check) select 'NREJBCF001' as jbcf_oid, 'NRE_Rapid_FileDownload' as job_name, 'RAPID_GS_EXTRACT_*.csv DataLoad' as job_desc, 'Fileload' as job_typ, 'MON,TUE,WED,THU,FRI,SAT,SUN' as job_run_day, '11:30' as job_start_time, '12:31' as job_end_time, '1' as job_run_freq, 150 as exp_run_dur, SYSDATE() as last_chg_tms, SYSDATE() as start_tms, NULL as end_tms, 'select max(job_id) as job_id, case when count(*) > 0 then reverse(split_part(reverse(max(job_input_txt)), ''/'', ''1'')) || '' is Loaded OK'' else ''RAPID_GS_EXTRACT_*.csv is not yet Loaded KO'' end as result from ft_t_jblg where job_input_txt ~ ''/RAPID_GS_EXTRACT_[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]_[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]_[0-9][0-9][0-9][0-9][0-9][0-9].csv'' and job_config_txt is null and job_start_tms::date = sysdate()::date' as in_query, NULL as pub_query, NULL as val_query, 'RESULT' as result_column, 'gsodmonitoring@thegoldensource.com,nuveenondemand@thegoldensource.com' as to_mail, 'ODAlerts@thegoldensource.com,nuveenondemand@thegoldensource.com' as info_mail, 'N' as task_start_check, 'N' as multi_check, 'N' as holiday_check, 'N' as range_check on conflict(jbcf_oid) where (jbcf_oid='NREJBCF001' and job_name='NRE_Rapid_FileDownload') do update set jbcf_oid = EXCLUDED.jbcf_oid, job_name = EXCLUDED.job_name, job_desc = EXCLUDED.job_desc, job_typ = EXCLUDED.job_typ, job_run_day = EXCLUDED.job_run_day, job_start_time = EXCLUDED.job_start_time, job_end_time = EXCLUDED.job_end_time, job_run_freq = EXCLUDED.job_run_freq, exp_run_dur = EXCLUDED.exp_run_dur, last_chg_tms = EXCLUDED.last_chg_tms, start_tms = EXCLUDED.start_tms, end_tms = EXCLUDED.end_tms, in_query = EXCLUDED.in_query, pub_query = EXCLUDED.pub_query, val_query = EXCLUDED.val_query, result_column = EXCLUDED.result_column, to_mail = EXCLUDED.to_mail, info_mail = EXCLUDED.info_mail, task_start_check = EXCLUDED.task_start_check, multi_check = EXCLUDED.multi_check, holiday_check = EXCLUDED.holiday_check, range_check = EXCLUDED.range_check;

-- CreditScope Muni
delete from ft_m_jbcf where jbcf_oid in ('CREDIT0001', 'CREDIT0002', 'CREDIT0003', 'CREDIT0004', 'CREDIT0005', 'CREDIT0006', 'CREDIT0007');

INSERT INTO ft_m_jbcf (jbcf_oid,job_name,job_desc,job_typ,job_run_day,job_start_time,job_end_time,job_run_freq,exp_run_dur,last_chg_tms,start_tms,end_tms,in_query,pub_query,val_query,result_column,to_mail,info_mail,task_start_check,multi_check,holiday_check,range_check)
select 'CREDIT0001','Nuveen CreditScope FileLoad','creditscope_goldensource*.csv Dataload','Fileload','MON,TUE,WED,THU,FRI','20:00','20:45','1',45,'2024-10-22 15:37:25.000','2024-10-22 15:37:25.000',NULL,'select max(job_id) as job_id , case when count(*) > 0 then  ''CreditScope Dataload Job is Loaded OK'' else ''CreditScope Dataload Job is not yet Loaded KO''  end as result from ft_t_jblg where job_id in (select max(prnt_job_id) from  ft_t_jblg where  job_input_txt ~* ''creditscope_goldensource.*\.csv'' and job_config_txt is null and job_start_tms::date = sysdate()::date and substring(job_input_txt from ''(([2][0][0-9][0-9])([1][0-2]|[0][1-9])([3][0-1]|[2][0-9]|[1][0-9]|[0][1-9]))'')::timestamp = ser_gs_gc.sysdate()::date and task_tot_cnt != task_failed_cnt and task_tot_cnt <> 0) and job_stat_typ  = ''CLOSED'' and job_config_txt =''CreditScope Dataload Job''',NULL,NULL,'RESULT','gsodmonitoring@thegoldensource.com,nuveenondemand@thegoldensource.com','ODAlerts@thegoldensource.com,nuveenondemand@thegoldensource.com','N','N','N','N'
from dual where not exists (select 'x' from ft_m_jbcf where job_name = 'Nuveen CreditScope FileLoad');

INSERT INTO ft_m_jbcf (jbcf_oid,job_name,job_desc,job_typ,job_run_day,job_start_time,job_end_time,job_run_freq,exp_run_dur,last_chg_tms,start_tms,end_tms,in_query,pub_query,val_query,result_column,to_mail,info_mail,task_start_check,multi_check,holiday_check,range_check)
select 'CREDIT0002','Nuveen Muni Eagle FileLoad','EAGLE_GS_SMF_SOI_EOD_*.txt Dataload','Fileload','MON,TUE,WED,THU,FRI','20:45','21:00','1',20,'2024-10-22 15:37:25.000','2024-10-22 15:37:25.000',NULL,'select max(job_id) as job_id , case when count(*) > 0 then  ''Eagle Muni Dataload Job is Loaded OK'' else ''Eagle Muni Dataload Job is not yet Loaded KO''  end as result from ft_t_jblg where job_id in (select max(prnt_job_id) from  ft_t_jblg where  job_input_txt ~* ''EAGLE_GS_SMF_SOI_EOD_.*txt'' and job_msg_typ ~* ''NuveenEagleMuniSOI'' and job_config_txt is null and job_start_tms::date = sysdate()::date and substring(job_input_txt from ''(([2][0][0-9][0-9])([1][0-2]|[0][1-9])([3][0-1]|[2][0-9]|[1][0-9]|[0][1-9]))'')::timestamp = ser_gs_gc.sysdate()::date and task_tot_cnt != task_failed_cnt and task_tot_cnt <> 0) and job_stat_typ  = ''CLOSED'' and job_config_txt =''Eagle Muni Dataload Job''',NULL,NULL,'RESULT','gsodmonitoring@thegoldensource.com,nuveenondemand@thegoldensource.com','ODAlerts@thegoldensource.com,nuveenondemand@thegoldensource.com','N','N','N','N'
from dual where not exists (select 'x' from ft_m_jbcf where job_name = 'Nuveen Muni Eagle FileLoad');

INSERT INTO ft_m_jbcf (jbcf_oid,job_name,job_desc,job_typ,job_run_day,job_start_time,job_end_time,job_run_freq,exp_run_dur,last_chg_tms,start_tms,end_tms,in_query,pub_query,val_query,result_column,to_mail,info_mail,task_start_check,multi_check,holiday_check,range_check)
select 'CREDIT0003','Nuveen Muni SNP Ratings Delta FileLoad','Muni Ratings SNP File Load Job','Fileload','MON,TUE,WED,THU,FRI','21:00','21:05','1',5,'2024-10-22 15:37:25.000','2024-10-22 15:37:25.000',NULL,'select max(job_id) as job_id , case when count(*) >= 1 then ''DeltaRating - SNP Rating Fileload Job Successfull!! OK'' else ''DeltaRating - SNP Rating Fileload Job not Successfull!! KO'' end as result from ft_t_jblg where job_id in ( select max(prnt_job_id) from ft_t_jblg where (UPPER(job_input_txt) ~* (UPPER(''.*security'')) and UPPER(bf_nme) ~* (UPPER(''S&P_XF_GR_Security_Ratings_NuveenMuni''))) and job_start_tms::date = sysdate()::date and substring(job_input_txt from ''(([2][0][0-9][0-9])([1][0-2]|[0][1-9])([3][0-1]|[2][0-9]|[1][0-9]|[0][1-9]))'')::timestamp = ser_gs_gc.sysdate()::date and task_tot_cnt != task_failed_cnt and task_tot_cnt <> 0) and job_stat_typ = ''CLOSED'' and job_config_txt = ''RATINGS_DELTA''',NULL,NULL,'RESULT','gsodmonitoring@thegoldensource.com,nuveenondemand@thegoldensource.com','ODAlerts@thegoldensource.com,nuveenondemand@thegoldensource.com','N','N','N','N'
from dual where not exists (select 'x' from ft_m_jbcf where job_name = 'Nuveen Muni SNP Ratings Delta FileLoad');

INSERT INTO ft_m_jbcf (jbcf_oid,job_name,job_desc,job_typ,job_run_day,job_start_time,job_end_time,job_run_freq,exp_run_dur,last_chg_tms,start_tms,end_tms,in_query,pub_query,val_query,result_column,to_mail,info_mail,task_start_check,multi_check,holiday_check,range_check)
select 'CREDIT0004','Nuveen Muni SMF Publish','CreditScope Muni Publish','Publishing','MON,TUE,WED,THU,FRI','21:15','21:20','1',5,'2024-10-22 15:37:25.000','2024-10-22 15:37:25.000',NULL,'select  max(job_id)  as job_id , case when count(*) > 0 then ''CreditScope Muni Publish Job Successfull!! OK'' else ''CreditScope Muni Publish Job not Successful!! KO'' end as result from ft_t_jblg where job_config_txt = ''Muni Publish'' and job_stat_typ  = ''CLOSED'' and job_start_tms::date = sysdate()::date',NULL,NULL,'RESULT','gsodmonitoring@thegoldensource.com,nuveenondemand@thegoldensource.com','ODAlerts@thegoldensource.com,nuveenondemand@thegoldensource.com','N','N','N','N'
from dual where not exists (select 'x' from ft_m_jbcf where job_name = 'Nuveen Muni SMF Publish');

INSERT INTO ft_m_jbcf (jbcf_oid,job_name,job_desc,job_typ,job_run_day,job_start_time,job_end_time,job_run_freq,exp_run_dur,last_chg_tms,start_tms,end_tms,in_query,pub_query,val_query,result_column,to_mail,info_mail,task_start_check,multi_check,holiday_check,range_check)
select 'CREDIT0005','Nuveen Muni Moodys Ratings Delta FileLoad','Muni Ratings MOODYS File Load Job','Fileload','MON,TUE,WED,THU,FRI','21:05','21:10','1',5,'2024-10-22 15:37:25.000','2024-10-22 15:37:25.000',NULL,'select max(job_id) as job_id, case when count(*) >= 1 then ''DeltaRating - MOODY Rating Fileload Job Successfull!! OK'' else ''DeltaRating - MOODY Rating Fileload Job not Successfull!! KO'' end as result from ft_t_jblg where job_id in ( select max(prnt_job_id) from ft_t_jblg where (UPPER(job_input_txt) ~* (UPPER(''pfg_inst_current_rating_.*_Utf8_24Hour_Delta_.*split'')) and UPPER(bf_nme) ~* (UPPER(''MoodysRDSInstrument_NuveenMuni''))) and job_start_tms::date = sysdate()::date and substring(job_input_txt from ''(([2][0][0-9][0-9])([1][0-2]|[0][1-9])([3][0-1]|[2][0-9]|[1][0-9]|[0][1-9]))'')::timestamp = ser_gs_gc.sysdate()::date and task_tot_cnt != task_failed_cnt and task_tot_cnt <> 0) and job_stat_typ = ''CLOSED''',NULL,NULL,'RESULT','gsodmonitoring@thegoldensource.com,nuveenondemand@thegoldensource.com','ODAlerts@thegoldensource.com,nuveenondemand@thegoldensource.com','N','N','N','N'
from dual where not exists (select 'x' from ft_m_jbcf where job_name = 'Nuveen Muni Moodys Ratings Delta FileLoad');

INSERT INTO ft_m_jbcf (jbcf_oid,job_name,job_desc,job_typ,job_run_day,job_start_time,job_end_time,job_run_freq,exp_run_dur,last_chg_tms,start_tms,end_tms,in_query,pub_query,val_query,result_column,to_mail,info_mail,task_start_check,multi_check,holiday_check,range_check)
select 'CREDIT0006','Nuveen Muni Fitch Ratings Delta FileLoad','Muni Ratings FITCH File Load Job','Fileload','MON,TUE,WED,THU,FRI','21:10','21:15','1',5,'2024-10-22 15:37:25.000','2024-10-22 15:37:25.000',NULL,'select max(job_id) as job_id, case when count(*) >= 1 then ''DeltaRating - FITCH Rating Fileload Job Successfull!! OK'' else ''DeltaRating - FITCH Rating Fileload Job not Successfull!! KO'' end as result from ft_t_jblg where job_id in ( select max(prnt_job_id) from ft_t_jblg where (UPPER(job_input_txt) ~* (UPPER(''RDSIssueReport.*dis'')) and UPPER(bf_nme) ~* (UPPER(''Fitch_RDS_Issue_Ratings_NuveenMuni''))) and job_start_tms::date = sysdate()::date and substring(job_input_txt from ''(([2][0][0-9][0-9])([1][0-2]|[0][1-9])([3][0-1]|[2][0-9]|[1][0-9]|[0][1-9]))'')::timestamp = ser_gs_gc.sysdate()::date and task_tot_cnt != task_failed_cnt and task_tot_cnt <> 0) and job_stat_typ = ''CLOSED''',NULL,NULL,'RESULT','gsodmonitoring@thegoldensource.com,nuveenondemand@thegoldensource.com','ODAlerts@thegoldensource.com,nuveenondemand@thegoldensource.com','N','N','N','N'
from dual where not exists (select 'x' from ft_m_jbcf where job_name = 'Nuveen Muni Fitch Ratings Delta FileLoad');

INSERT INTO ft_m_jbcf (jbcf_oid,job_name,job_desc,job_typ,job_run_day,job_start_time,job_end_time,job_run_freq,exp_run_dur,last_chg_tms,start_tms,end_tms,in_query,pub_query,val_query,result_column,to_mail,info_mail,task_start_check,multi_check,holiday_check,range_check)
select 'CREDIT0007','Nuveen Muni Issuer Publish','CreditScope Muni Issuer Publish','Publishing','MON,TUE,WED,THU,FRI','21:20','21:25','1',5,'2024-10-22 15:37:25.000','2024-10-22 15:37:25.000',NULL,'select  max(job_id)  as job_id , case when count(*) > 0 then ''CreditScope Muni Issuer Publish Job Successfull!! OK'' else ''CreditScope Muni Issuer Publish Job not Successful!! KO'' end as result from ft_t_jblg where job_config_txt = ''Muni Issuer Publish'' and job_stat_typ  = ''CLOSED'' and job_start_tms::date = sysdate()::date',NULL,NULL,'RESULT','gsodmonitoring@thegoldensource.com,nuveenondemand@thegoldensource.com','ODAlerts@thegoldensource.com,nuveenondemand@thegoldensource.com','N','N','N','N'
from dual where not exists (select 'x' from ft_m_jbcf where job_name = 'Nuveen Muni Issuer Publish');
