INSERT INTO  ft_m_jbcf
(jbcf_oid, job_name, job_desc, job_typ, job_run_day, job_start_time, job_end_time, job_run_freq, exp_run_dur, last_chg_tms, start_tms, end_tms, in_query, pub_query, val_query, result_column, to_mail, info_mail, task_start_check, multi_check, holiday_check, range_check)
select 'CREDIT0001', 'Nuveen_CreditScope_Load_Process', 'creditscope_goldensource*.csv Dataload', 'Fileload', 'MON,TUE,WED,THU,FRI,SAT', '20:00', '20:31', '1', 25, SYSDATE(), SYSDATE(), NULL, 'select max(job_id) as job_id , case when count(*) > 0 then  ''CreditScope Dataload Job is Loaded OK'' else ''CreditScope Dataload Job is not yet Loaded KO''  end as result from ft_t_jblg where job_id in (select max(prnt_job_id) from  ft_t_jblg where  job_input_txt ~* ''creditscope_goldensource.*\.csv'' and job_config_txt is null  and job_start_tms::date >= sysdate()::date ) and job_stat_typ  = ''CLOSED'' and job_config_txt =''CreditScope Dataload Job''' , NULL, NULL, 'RESULT', 'gsodmonitoring@thegoldensource.com,nuveenondemand@thegoldensource.com,adhaker@thegoldensource.com', 'ODAlerts@thegoldensource.com,nuveenondemand@thegoldensource.com,adhaker@thegoldensource.com', 'N', 'N', 'N', 'N' 
from dual where not exists (select 'x' from ft_m_jbcf where job_name = 'Nuveen_CreditScope_Load_Process');


INSERT INTO  ft_m_jbcf
(jbcf_oid, job_name, job_desc, job_typ, job_run_day, job_start_time, job_end_time, job_run_freq, exp_run_dur, last_chg_tms, start_tms, end_tms, in_query, pub_query, val_query, result_column, to_mail, info_mail, task_start_check, multi_check, holiday_check, range_check)
select 'CREDIT0002', 'Nuveen_Muni_Eagle_Load_Process', 'EAGLE_GS_SMF_SOI_EOD_*.txt Dataload', 'Fileload', 'MON,TUE,WED,THU,FRI,SAT', '20:30', '21:01', '1', 25, SYSDATE(), SYSDATE(), NULL, 'select max(job_id) as job_id , case when count(*) > 0 then  ''Eagle Muni Dataload Job is Loaded OK'' else ''Eagle Muni Dataload Job is not yet Loaded KO''  end as result from ft_t_jblg where job_id in (select max(prnt_job_id) from  ft_t_jblg where  job_input_txt ~* ''EAGLE_GS_SMF_SOI_EOD_*\.txt'' or job_msg_typ ~* ''NuveenEagleMuniSOI'' and job_config_txt is null and job_start_tms::date >= sysdate()::date ) and job_stat_typ  = ''CLOSED'' and job_config_txt =''Eagle Muni Dataload Job''', NULL, NULL, 'RESULT', 'gsodmonitoring@thegoldensource.com,nuveenondemand@thegoldensource.com,adhaker@thegoldensource.com', 'ODAlerts@thegoldensource.com,nuveenondemand@thegoldensource.com,adhaker@thegoldensource.com', 'N', 'N', 'N', 'N' 
from dual where not exists (select 'x' from ft_m_jbcf where job_name = 'Nuveen_Muni_Eagle_Load_Process');

INSERT INTO  ft_m_jbcf
(jbcf_oid, job_name, job_desc, job_typ, job_run_day, job_start_time, job_end_time, job_run_freq, exp_run_dur, last_chg_tms, start_tms, end_tms, in_query, pub_query, val_query, result_column, to_mail, info_mail, task_start_check, multi_check, holiday_check, range_check)
select 'CREDIT0003', 'Nuveen_Muni_Ratings_Delta_Load_Process', 'Muni Ratings SNP File Load Job', 'Fileload', 'MON,TUE,WED,THU,FRI', '21:00', '22:30', '1', 90, SYSDATE(), SYSDATE(), NULL, 'select max(job_id) as job_id , case when count(*) >=1 then ''DeltaRating - SNP Rating Fileload Job Successfull!! OK'' else ''DeltaRating - SNP Rating Fileload Job not Successfull!! KO''  end as result from ft_t_jblg where job_stat_typ  = ''CLOSED'' and job_start_tms::date >= sysdate()::date and job_config_txt =''RATINGS_DELTA''' , NULL, NULL, 'RESULT', 'gsodmonitoring@thegoldensource.com,nuveenondemand@thegoldensource.com,adhaker@thegoldensource.com', 'ODAlerts@thegoldensource.com,nuveenondemand@thegoldensource.com,adhaker@thegoldensource.com', 'N', 'N', 'N', 'N' 
from dual where not exists (select 'x' from ft_m_jbcf where job_name = 'Nuveen_Muni_Ratings_Delta_Load_Process');

INSERT INTO  ft_m_jbcf
(jbcf_oid, job_name, job_desc, job_typ, job_run_day, job_start_time, job_end_time, job_run_freq, exp_run_dur, last_chg_tms, start_tms, end_tms, in_query, pub_query, val_query, result_column, to_mail, info_mail, task_start_check, multi_check, holiday_check, range_check)
select 'CREDIT0004', 'Nuveen_CreditScope_Publish_Process', 'CreditScope Muni Publish', 'Publishing', 'MON,TUE,WED,THU,FRI', '22:00', '23:30', '1', 40, SYSDATE(), SYSDATE(), NULL, 'select  max(job_id)  as job_id , case when count(*) > 0 then ''CreditScope Muni Publish Job Successfull!! OK'' else ''CreditScope Muni Publish Job not Successful!! KO'' end as result from ft_t_jblg where job_config_txt = ''Muni Publish'' and job_stat_typ  = ''CLOSED'' and job_start_tms::date >= sysdate()::date', NULL, NULL, 'RESULT', 'gsodmonitoring@thegoldensource.com,nuveenondemand@thegoldensource.com,adhaker@thegoldensource.com', 'ODAlerts@thegoldensource.com,nuveenondemand@thegoldensource.com,adhaker@thegoldensource.com', 'N', 'N', 'N', 'N' 
from dual where not exists (select 'x' from ft_m_jbcf where job_name = 'Nuveen_CreditScope_Publish_Process');

INSERT INTO  ft_m_jbcf
(jbcf_oid, job_name, job_desc, job_typ, job_run_day, job_start_time, job_end_time, job_run_freq, exp_run_dur, last_chg_tms, start_tms, end_tms, in_query, pub_query, val_query, result_column, to_mail, info_mail, task_start_check, multi_check, holiday_check, range_check)
select 'CREDIT0005', 'Nuveen_Muni_Ratings_Delta_Load_Process1', 'Muni Ratings MOODYS File Load Job', 'Fileload', 'MON,TUE,WED,THU,FRI', '21:00', '22:30', '1', 90, SYSDATE(), SYSDATE(), NULL, 'select max(job_id) as job_id , case when count(*) >=1 then ''DeltaRating - MOODY Rating Fileload Job Successfull!! OK'' else ''DeltaRating - MOODY Rating Fileload Job not Successfull!! KO''  end as result from ft_t_jblg where job_input_txt ~* ''pfg_inst_current_rating_00_Utf8_24Hour_Delta*'' and job_start_tms::date >= sysdate()::date and job_end_tms is not null and job_stat_typ = ''CLOSED''' , NULL, NULL, 'RESULT', 'gsodmonitoring@thegoldensource.com,nuveenondemand@thegoldensource.com,adhaker@thegoldensource.com', 'ODAlerts@thegoldensource.com,nuveenondemand@thegoldensource.com,adhaker@thegoldensource.com', 'N', 'N', 'N', 'N' 
from dual where not exists (select 'x' from ft_m_jbcf where job_name = 'Nuveen_Muni_Ratings_Delta_Load_Process1');

INSERT INTO  ft_m_jbcf
(jbcf_oid, job_name, job_desc, job_typ, job_run_day, job_start_time, job_end_time, job_run_freq, exp_run_dur, last_chg_tms, start_tms, end_tms, in_query, pub_query, val_query, result_column, to_mail, info_mail, task_start_check, multi_check, holiday_check, range_check)
select 'CREDIT0006', 'Nuveen_Muni_Ratings_Delta_Load_Process2', 'Muni Ratings FITCH File Load Job', 'Fileload', 'MON,TUE,WED,THU,FRI', '21:00', '22:30', '1', 90, SYSDATE(), SYSDATE(), NULL, 'select max(job_id) as job_id , case when count(*) >=1 then ''DeltaRating - FITCH Rating Fileload Job Successfull!! OK'' else ''DeltaRating - FITCH Rating Fileload Job not Successfull!! KO''  end as result from ft_t_jblg where job_input_txt ~* ''RDSIssueReport*'' and job_start_tms::date >= sysdate()::date and job_end_tms is not null and job_stat_typ = ''CLOSED''' , NULL, NULL, 'RESULT', 'gsodmonitoring@thegoldensource.com,nuveenondemand@thegoldensource.com,adhaker@thegoldensource.com', 'ODAlerts@thegoldensource.com,nuveenondemand@thegoldensource.com,adhaker@thegoldensource.com', 'N', 'N', 'N', 'N' 
from dual where not exists (select 'x' from ft_m_jbcf where job_name = 'Nuveen_Muni_Ratings_Delta_Load_Process2');

INSERT INTO  ft_m_jbcf
(jbcf_oid, job_name, job_desc, job_typ, job_run_day, job_start_time, job_end_time, job_run_freq, exp_run_dur, last_chg_tms, start_tms, end_tms, in_query, pub_query, val_query, result_column, to_mail, info_mail, task_start_check, multi_check, holiday_check, range_check)
select 'CREDIT0007', 'Nuveen_CreditScope_Publish_Process1', 'CreditScope Muni Issuer Publish', 'Publishing', 'MON,TUE,WED,THU,FRI', '22:00', '23:30', '1', 40, SYSDATE(), SYSDATE(), NULL, 'select  max(job_id)  as job_id , case when count(*) > 0 then ''CreditScope Muni Issuer Publish Job Successfull!! OK'' else ''CreditScope Muni Issuer Publish Job not Successful!! KO'' end as result from ft_t_jblg where job_config_txt = ''Muni Issuer Publish'' and job_stat_typ  = ''CLOSED'' and job_start_tms::date >= sysdate()::date', NULL, NULL, 'RESULT', 'gsodmonitoring@thegoldensource.com,nuveenondemand@thegoldensource.com,adhaker@thegoldensource.com', 'ODAlerts@thegoldensource.com,nuveenondemand@thegoldensource.com,adhaker@thegoldensource.com', 'N', 'N', 'N', 'N' 
from dual where not exists (select 'x' from ft_m_jbcf where job_name = 'Nuveen_CreditScope_Publish_Process1');