--Exchange codes customized for Nuveen -- added to SVN on 1126
--To be executed only once through PD
--MaaF process should not be run on the Nuveen Schema as the customization of exchanges will be misaligned.



INSERT INTO ft_t_mrkt
(mkt_oid, gu_id, gu_typ, gu_cnt, inst_mnem, prnt_mkt_oid, created_tms, last_chg_tms, last_chg_usr_id, end_tms, curr_mid_of_cnt, days_mth_bas_typ, days_yr_bas_typ, day_settle_buy_qty, day_settle_sll_qty, csd_permit_ind, pref_settle_cde, pref_trdng_cde, pref_iss_ctxt_typ, start_bus_dy_tme, end_bus_dy_tme, local_tmz, mkt_nme, mkt_desc, mkt_trdng_stat_typ, mkt_making_typ, phys_trdng_ind, elec_trdng_ind, elec_match_ind, trd_lot_size_cqty, nls_cde, data_stat_typ, data_src_id, data_coverage_typ, mail_addr_id, elec_addr_id, mkt_stat_typ, rnd_lot_sz_cqty, dy_chg_lmt_camt, held_pos_lmt_camt, mkt_listed_ind, rnd_lot_dependent_ind, mifid_regulated_ind, merge_uniq_oid, fins_mkt_typ, pref_settle_typ, pref_interface_typ, pref_placement_typ, order_cut_off_tme, trd_dte_acrd_int_ind, auto_order_expire_ind, mkt_quote_typ, internet_trdng_ind, trdbot_dy_typ, trdbot_dy_num, trdbot_strt_num, pref_mkt_id, pref_mkt_id_ctxt_typ, mic_mkt_lvl_typ, brokered_mrkt_ind, gunt_oid, part_oid)
SELECT '=000854458', 'GB', 'COUNTRY', 1, NULL, NULL, SYSDATE(), SYSDATE(), 'NUVEEN:CSTM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'GBP', NULL, NULL, NULL, NULL, 'London Intl', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ACTIVE', 'ISO10383', NULL, NULL, NULL, NULL, 1.00000000000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'O', NULL, 'GUNT3EA===', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_mrkt WHERE gu_id = 'GB' AND mkt_nme = 'London Intl');
INSERT INTO ft_t_mrkt
(mkt_oid, gu_id, gu_typ, gu_cnt, inst_mnem, prnt_mkt_oid, created_tms, last_chg_tms, last_chg_usr_id, end_tms, curr_mid_of_cnt, days_mth_bas_typ, days_yr_bas_typ, day_settle_buy_qty, day_settle_sll_qty, csd_permit_ind, pref_settle_cde, pref_trdng_cde, pref_iss_ctxt_typ, start_bus_dy_tme, end_bus_dy_tme, local_tmz, mkt_nme, mkt_desc, mkt_trdng_stat_typ, mkt_making_typ, phys_trdng_ind, elec_trdng_ind, elec_match_ind, trd_lot_size_cqty, nls_cde, data_stat_typ, data_src_id, data_coverage_typ, mail_addr_id, elec_addr_id, mkt_stat_typ, rnd_lot_sz_cqty, dy_chg_lmt_camt, held_pos_lmt_camt, mkt_listed_ind, rnd_lot_dependent_ind, mifid_regulated_ind, merge_uniq_oid, fins_mkt_typ, pref_settle_typ, pref_interface_typ, pref_placement_typ, order_cut_off_tme, trd_dte_acrd_int_ind, auto_order_expire_ind, mkt_quote_typ, internet_trdng_ind, trdbot_dy_typ, trdbot_dy_num, trdbot_strt_num, pref_mkt_id, pref_mkt_id_ctxt_typ, mic_mkt_lvl_typ, brokered_mrkt_ind, gunt_oid, part_oid)
SELECT '=000854457', 'GB', 'COUNTRY', 1, NULL, NULL, SYSDATE(), SYSDATE(), 'NUVEEN:CSTM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'GBP', NULL, NULL, NULL, NULL, 'LSE EuropeQS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ACTIVE', 'ISO10383', NULL, NULL, NULL, NULL, 1.00000000000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'O', NULL, 'GUNT3EA===', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_mrkt WHERE gu_id = 'GB' AND mkt_nme = 'LSE EuropeQS');
INSERT INTO ft_t_mrkt
(mkt_oid, gu_id, gu_typ, gu_cnt, inst_mnem, prnt_mkt_oid, created_tms, last_chg_tms, last_chg_usr_id, end_tms, curr_mid_of_cnt, days_mth_bas_typ, days_yr_bas_typ, day_settle_buy_qty, day_settle_sll_qty, csd_permit_ind, pref_settle_cde, pref_trdng_cde, pref_iss_ctxt_typ, start_bus_dy_tme, end_bus_dy_tme, local_tmz, mkt_nme, mkt_desc, mkt_trdng_stat_typ, mkt_making_typ, phys_trdng_ind, elec_trdng_ind, elec_match_ind, trd_lot_size_cqty, nls_cde, data_stat_typ, data_src_id, data_coverage_typ, mail_addr_id, elec_addr_id, mkt_stat_typ, rnd_lot_sz_cqty, dy_chg_lmt_camt, held_pos_lmt_camt, mkt_listed_ind, rnd_lot_dependent_ind, mifid_regulated_ind, merge_uniq_oid, fins_mkt_typ, pref_settle_typ, pref_interface_typ, pref_placement_typ, order_cut_off_tme, trd_dte_acrd_int_ind, auto_order_expire_ind, mkt_quote_typ, internet_trdng_ind, trdbot_dy_typ, trdbot_dy_num, trdbot_strt_num, pref_mkt_id, pref_mkt_id_ctxt_typ, mic_mkt_lvl_typ, brokered_mrkt_ind, gunt_oid, part_oid)
SELECT '=000854456', 'BR', 'COUNTRY', 1, NULL, NULL, SYSDATE(), SYSDATE(), 'NUVEEN:CSTM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'BRL', NULL, NULL, NULL, NULL, 'SOMA', 'SOMA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ACTIVE', 'ISO10383', NULL, NULL, NULL, NULL, 1.00000000000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'O', NULL, 'GUNT254===', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_mrkt WHERE gu_id = 'BR' AND mkt_nme = 'SOMA');
INSERT INTO ft_t_mrkt
(mkt_oid, gu_id, gu_typ, gu_cnt, inst_mnem, prnt_mkt_oid, created_tms, last_chg_tms, last_chg_usr_id, end_tms, curr_mid_of_cnt, days_mth_bas_typ, days_yr_bas_typ, day_settle_buy_qty, day_settle_sll_qty, csd_permit_ind, pref_settle_cde, pref_trdng_cde, pref_iss_ctxt_typ, start_bus_dy_tme, end_bus_dy_tme, local_tmz, mkt_nme, mkt_desc, mkt_trdng_stat_typ, mkt_making_typ, phys_trdng_ind, elec_trdng_ind, elec_match_ind, trd_lot_size_cqty, nls_cde, data_stat_typ, data_src_id, data_coverage_typ, mail_addr_id, elec_addr_id, mkt_stat_typ, rnd_lot_sz_cqty, dy_chg_lmt_camt, held_pos_lmt_camt, mkt_listed_ind, rnd_lot_dependent_ind, mifid_regulated_ind, merge_uniq_oid, fins_mkt_typ, pref_settle_typ, pref_interface_typ, pref_placement_typ, order_cut_off_tme, trd_dte_acrd_int_ind, auto_order_expire_ind, mkt_quote_typ, internet_trdng_ind, trdbot_dy_typ, trdbot_dy_num, trdbot_strt_num, pref_mkt_id, pref_mkt_id_ctxt_typ, mic_mkt_lvl_typ, brokered_mrkt_ind, gunt_oid, part_oid)
SELECT '=000854455', 'BR', 'COUNTRY', 1, NULL, NULL, SYSDATE(), SYSDATE(), 'NUVEEN:CSTM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'BRL', NULL, NULL, NULL, NULL, 'BOLSA DE VALORES DO ESTADO DE SAO PAULO (BRAZIL)', 'BOLSA DE VALORES DO ESTADO DE SAO PAULO (BRAZIL)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ACTIVE', 'ISO10383', NULL, NULL, NULL, NULL, 1.00000000000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'O', NULL, 'GUNT254===', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_mrkt WHERE gu_id = 'BR' AND mkt_nme = 'BOLSA DE VALORES DO ESTADO DE SAO PAULO (BRAZIL)');
INSERT INTO ft_t_mrkt
(mkt_oid, gu_id, gu_typ, gu_cnt, inst_mnem, prnt_mkt_oid, created_tms, last_chg_tms, last_chg_usr_id, end_tms, curr_mid_of_cnt, days_mth_bas_typ, days_yr_bas_typ, day_settle_buy_qty, day_settle_sll_qty, csd_permit_ind, pref_settle_cde, pref_trdng_cde, pref_iss_ctxt_typ, start_bus_dy_tme, end_bus_dy_tme, local_tmz, mkt_nme, mkt_desc, mkt_trdng_stat_typ, mkt_making_typ, phys_trdng_ind, elec_trdng_ind, elec_match_ind, trd_lot_size_cqty, nls_cde, data_stat_typ, data_src_id, data_coverage_typ, mail_addr_id, elec_addr_id, mkt_stat_typ, rnd_lot_sz_cqty, dy_chg_lmt_camt, held_pos_lmt_camt, mkt_listed_ind, rnd_lot_dependent_ind, mifid_regulated_ind, merge_uniq_oid, fins_mkt_typ, pref_settle_typ, pref_interface_typ, pref_placement_typ, order_cut_off_tme, trd_dte_acrd_int_ind, auto_order_expire_ind, mkt_quote_typ, internet_trdng_ind, trdbot_dy_typ, trdbot_dy_num, trdbot_strt_num, pref_mkt_id, pref_mkt_id_ctxt_typ, mic_mkt_lvl_typ, brokered_mrkt_ind, gunt_oid, part_oid)
SELECT '=000854454', 'NG', 'COUNTRY', 1, NULL, NULL, SYSDATE(), SYSDATE(), 'NUVEEN:CSTM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NGN', NULL, NULL, NULL, NULL, 'NIGERIAN STOCK EXCHANGE', 'NIGERIAN STOCK EXCHANGE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ACTIVE', 'ISO10383', NULL, NULL, NULL, NULL, 1.00000000000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'O', NULL, 'GUNT2ED===', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_mrkt WHERE gu_id = 'NG' AND mkt_nme = 'NIGERIAN STOCK EXCHANGE');
INSERT INTO ft_t_mrkt
(mkt_oid, gu_id, gu_typ, gu_cnt, inst_mnem, prnt_mkt_oid, created_tms, last_chg_tms, last_chg_usr_id, end_tms, curr_mid_of_cnt, days_mth_bas_typ, days_yr_bas_typ, day_settle_buy_qty, day_settle_sll_qty, csd_permit_ind, pref_settle_cde, pref_trdng_cde, pref_iss_ctxt_typ, start_bus_dy_tme, end_bus_dy_tme, local_tmz, mkt_nme, mkt_desc, mkt_trdng_stat_typ, mkt_making_typ, phys_trdng_ind, elec_trdng_ind, elec_match_ind, trd_lot_size_cqty, nls_cde, data_stat_typ, data_src_id, data_coverage_typ, mail_addr_id, elec_addr_id, mkt_stat_typ, rnd_lot_sz_cqty, dy_chg_lmt_camt, held_pos_lmt_camt, mkt_listed_ind, rnd_lot_dependent_ind, mifid_regulated_ind, merge_uniq_oid, fins_mkt_typ, pref_settle_typ, pref_interface_typ, pref_placement_typ, order_cut_off_tme, trd_dte_acrd_int_ind, auto_order_expire_ind, mkt_quote_typ, internet_trdng_ind, trdbot_dy_typ, trdbot_dy_num, trdbot_strt_num, pref_mkt_id, pref_mkt_id_ctxt_typ, mic_mkt_lvl_typ, brokered_mrkt_ind, gunt_oid, part_oid)
SELECT '=000854453', 'JP', 'COUNTRY', 1, NULL, NULL, SYSDATE(), SYSDATE(), 'NUVEEN:CSTM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'JPY', NULL, NULL, NULL, NULL, 'Nuveen OSAKA EXCHANGE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ACTIVE', 'ISO10383', NULL, NULL, NULL, NULL, 1000.00000000000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'S', NULL, 'GUNT423===', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_mrkt WHERE gu_id = 'JP' AND mkt_nme = 'Nuveen OSAKA EXCHANGE');
INSERT INTO ft_t_mrkt
(mkt_oid, gu_id, gu_typ, gu_cnt, inst_mnem, prnt_mkt_oid, created_tms, last_chg_tms, last_chg_usr_id, end_tms, curr_mid_of_cnt, days_mth_bas_typ, days_yr_bas_typ, day_settle_buy_qty, day_settle_sll_qty, csd_permit_ind, pref_settle_cde, pref_trdng_cde, pref_iss_ctxt_typ, start_bus_dy_tme, end_bus_dy_tme, local_tmz, mkt_nme, mkt_desc, mkt_trdng_stat_typ, mkt_making_typ, phys_trdng_ind, elec_trdng_ind, elec_match_ind, trd_lot_size_cqty, nls_cde, data_stat_typ, data_src_id, data_coverage_typ, mail_addr_id, elec_addr_id, mkt_stat_typ, rnd_lot_sz_cqty, dy_chg_lmt_camt, held_pos_lmt_camt, mkt_listed_ind, rnd_lot_dependent_ind, mifid_regulated_ind, merge_uniq_oid, fins_mkt_typ, pref_settle_typ, pref_interface_typ, pref_placement_typ, order_cut_off_tme, trd_dte_acrd_int_ind, auto_order_expire_ind, mkt_quote_typ, internet_trdng_ind, trdbot_dy_typ, trdbot_dy_num, trdbot_strt_num, pref_mkt_id, pref_mkt_id_ctxt_typ, mic_mkt_lvl_typ, brokered_mrkt_ind, gunt_oid, part_oid)
SELECT '=000854451', 'AU', 'COUNTRY', 1, NULL, NULL, SYSDATE(), SYSDATE(), 'NUVEEN:CSTM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'AUD', NULL, NULL, NULL, NULL, 'AUSTRALIA-MELBOURNE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ACTIVE', 'ISO10383', NULL, NULL, NULL, NULL, 1.00000000000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'O', NULL, 'GUNT27A===', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_mrkt WHERE gu_id = 'AU' AND mkt_nme = 'AUSTRALIA-MELBOURNE');
INSERT INTO ft_t_mrkt
(mkt_oid, gu_id, gu_typ, gu_cnt, inst_mnem, prnt_mkt_oid, created_tms, last_chg_tms, last_chg_usr_id, end_tms, curr_mid_of_cnt, days_mth_bas_typ, days_yr_bas_typ, day_settle_buy_qty, day_settle_sll_qty, csd_permit_ind, pref_settle_cde, pref_trdng_cde, pref_iss_ctxt_typ, start_bus_dy_tme, end_bus_dy_tme, local_tmz, mkt_nme, mkt_desc, mkt_trdng_stat_typ, mkt_making_typ, phys_trdng_ind, elec_trdng_ind, elec_match_ind, trd_lot_size_cqty, nls_cde, data_stat_typ, data_src_id, data_coverage_typ, mail_addr_id, elec_addr_id, mkt_stat_typ, rnd_lot_sz_cqty, dy_chg_lmt_camt, held_pos_lmt_camt, mkt_listed_ind, rnd_lot_dependent_ind, mifid_regulated_ind, merge_uniq_oid, fins_mkt_typ, pref_settle_typ, pref_interface_typ, pref_placement_typ, order_cut_off_tme, trd_dte_acrd_int_ind, auto_order_expire_ind, mkt_quote_typ, internet_trdng_ind, trdbot_dy_typ, trdbot_dy_num, trdbot_strt_num, pref_mkt_id, pref_mkt_id_ctxt_typ, mic_mkt_lvl_typ, brokered_mrkt_ind, gunt_oid, part_oid)
SELECT '=000854450', 'IN', 'COUNTRY', 1, NULL, NULL, SYSDATE(), SYSDATE(), 'NUVEEN:CSTM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'INR', NULL, NULL, NULL, NULL, 'Nuveen BSE LTD', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ACTIVE', 'NUVEEN', NULL, NULL, NULL, NULL, 1.00000000000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'O', NULL, 'GUNT342===', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_mrkt WHERE gu_id = 'IN' AND mkt_nme = 'Nuveen BSE LTD');


INSERT INTO ft_t_mrkt
(mkt_oid, gu_id, gu_typ, gu_cnt, inst_mnem, prnt_mkt_oid, created_tms, last_chg_tms, last_chg_usr_id, end_tms, curr_mid_of_cnt, days_mth_bas_typ, days_yr_bas_typ, day_settle_buy_qty, day_settle_sll_qty, csd_permit_ind, pref_settle_cde, pref_trdng_cde, pref_iss_ctxt_typ, start_bus_dy_tme, end_bus_dy_tme, local_tmz, mkt_nme, mkt_desc, mkt_trdng_stat_typ, mkt_making_typ, phys_trdng_ind, elec_trdng_ind, elec_match_ind, trd_lot_size_cqty, nls_cde, data_stat_typ, data_src_id, data_coverage_typ, mail_addr_id, elec_addr_id, mkt_stat_typ, rnd_lot_sz_cqty, dy_chg_lmt_camt, held_pos_lmt_camt, mkt_listed_ind, rnd_lot_dependent_ind, mifid_regulated_ind, merge_uniq_oid, fins_mkt_typ, pref_settle_typ, pref_interface_typ, pref_placement_typ, order_cut_off_tme, trd_dte_acrd_int_ind, auto_order_expire_ind, mkt_quote_typ, internet_trdng_ind, trdbot_dy_typ, trdbot_dy_num, trdbot_strt_num, pref_mkt_id, pref_mkt_id_ctxt_typ, mic_mkt_lvl_typ, brokered_mrkt_ind, gunt_oid, part_oid)
SELECT '=000903750', 'US', 'COUNTRY', 1, NULL, NULL, SYSDATE(), SYSDATE(), 'NUVEEN:CSTM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'USD', NULL, NULL, NULL, NULL, 'NEW YORK OTC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ACTIVE', 'ISO10383', NULL, NULL, NULL, NULL, 100.00000000000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'O', NULL, 'GUNT3CC===', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_mrkt WHERE gu_id = 'US' AND mkt_nme = 'NEW YORK OTC');

--order changed of the delete script.
delete from ft_t_mrkt where mkt_nme = 'NEW YORK OTC' and gu_id = 'US' and mkt_oid <> '=000903750';