Insert into FT_T_CLDF(TBL_ID,LAST_CHG_TMS,LAST_CHG_USR_ID,COL_NME,FLD_ID,COL_REQ_IND,DDL_DATA_TYP,COL_SQ_NUM,LOGL_NME,COL_DESC,DDL_BASE_DATA_TYP,DDL_DATA_LEN,DDL_DATA_PREC_NUM,DDL_DATA_SCALE_NUM,DDL_DATA_DFLT_TXT,COL_VIEW_NME,INFO_TYP_NME,DSPY_CAPTION_TXT)select 'RRC1',CURRENT_TIMESTAMP,'NUVEEN:CSTM','RRC1_OID','RRC10001','Y','VARCHAR(10)',1,'Rating Recon Identifier','Rating Recon Identifier','VARCHAR',10,0,0,null,'RRC1_OID','OBJECT_IDENTIFIER','Rating Recon Identifier' FROM DUAL WHERE NOT EXISTS
(SELECT 1 FROM FT_T_CLDF WHERE TBL_ID ='RRC1' AND COL_NME='RRC1_OID' );

Insert into FT_T_CLDF(TBL_ID,LAST_CHG_TMS,LAST_CHG_USR_ID,COL_NME,FLD_ID,COL_REQ_IND,DDL_DATA_TYP,COL_SQ_NUM,LOGL_NME,COL_DESC,DDL_BASE_DATA_TYP,DDL_DATA_LEN,DDL_DATA_PREC_NUM,DDL_DATA_SCALE_NUM,DDL_DATA_DFLT_TXT,COL_VIEW_NME,INFO_TYP_NME,DSPY_CAPTION_TXT)select 'RRC1',CURRENT_TIMESTAMP,'NUVEEN:CSTM','ISS_RTNG_OID','00101325','N','VARCHAR(10)',2,'Issue Rating OID','This field contains an arbitrary value that uniquely identifies an occurrence of the Issue Rating table. This value is typically programmatically generated.','VARCHAR',10,0,0,null,'ISS_RTNG_OID','OBJECT_IDENTIFIER',NULL 
FROM DUAL WHERE NOT EXISTS
(SELECT 1 FROM FT_T_CLDF WHERE TBL_ID ='RRC1' AND COL_NME='ISS_RTNG_OID' );

Insert into FT_T_CLDF(TBL_ID,LAST_CHG_TMS,LAST_CHG_USR_ID,COL_NME,FLD_ID,COL_REQ_IND,DDL_DATA_TYP,COL_SQ_NUM,LOGL_NME,COL_DESC,DDL_BASE_DATA_TYP,DDL_DATA_LEN,DDL_DATA_PREC_NUM,DDL_DATA_SCALE_NUM,DDL_DATA_DFLT_TXT,COL_VIEW_NME,INFO_TYP_NME,DSPY_CAPTION_TXT)select 'RRC1',CURRENT_TIMESTAMP,'NUVEEN:CSTM','FINS_RTNG_OID','00101065','N','VARCHAR(10)',3,'Fins Rating OID','This field contains an arbitrary value that uniquely identifies an occurrence of the Financial Institution Rating table. This value is typically programmatically generated.','VARCHAR',10,0,0,null,'FINS_RTNG_OID','OBJECT_IDENTIFIER',NULL
FROM DUAL WHERE NOT EXISTS
(SELECT 1 FROM FT_T_CLDF WHERE TBL_ID ='RRC1' AND COL_NME='FINS_RTNG_OID' );

Insert into FT_T_CLDF(TBL_ID,LAST_CHG_TMS,LAST_CHG_USR_ID,COL_NME,FLD_ID,COL_REQ_IND,DDL_DATA_TYP,COL_SQ_NUM,LOGL_NME,COL_DESC,DDL_BASE_DATA_TYP,DDL_DATA_LEN,DDL_DATA_PREC_NUM,DDL_DATA_SCALE_NUM,DDL_DATA_DFLT_TXT,COL_VIEW_NME,INFO_TYP_NME,DSPY_CAPTION_TXT)select 'RRC1',CURRENT_TIMESTAMP,'NUVEEN:CSTM','RTOP_OID','01851048','N','VARCHAR(10)',4,'Rating Opinions OID','This field contains an arbitrary value that uniquely identifies an occurrence of the Rating Opinions table. This value is typically programmatically generated.','VARCHAR',10,0,0,null,'RTOP_OID','OBJECT_IDENTIFIER',NULL
FROM DUAL WHERE NOT EXISTS
(SELECT 1 FROM FT_T_CLDF WHERE TBL_ID ='RRC1' AND COL_NME='RTOP_OID' );

Insert into FT_T_CLDF(TBL_ID,LAST_CHG_TMS,LAST_CHG_USR_ID,COL_NME,FLD_ID,COL_REQ_IND,DDL_DATA_TYP,COL_SQ_NUM,LOGL_NME,COL_DESC,DDL_BASE_DATA_TYP,DDL_DATA_LEN,DDL_DATA_PREC_NUM,DDL_DATA_SCALE_NUM,DDL_DATA_DFLT_TXT,COL_VIEW_NME,INFO_TYP_NME,DSPY_CAPTION_TXT)select 'RRC1',CURRENT_TIMESTAMP,'NUVEEN:CSTM','TBL_ID','00074268','Y','VARCHAR(4)',5,'Table ID','This field contains a mnemonic that uniquely identifies a table.','VARCHAR',4,0,0,null,'Table_ID','TABLE_TYPE',NULL
FROM DUAL WHERE NOT EXISTS
(SELECT 1 FROM FT_T_CLDF WHERE TBL_ID ='RRC1' AND COL_NME='TBL_ID' );

Insert into FT_T_CLDF(TBL_ID,LAST_CHG_TMS,LAST_CHG_USR_ID,COL_NME,FLD_ID,COL_REQ_IND,DDL_DATA_TYP,COL_SQ_NUM,LOGL_NME,COL_DESC,DDL_BASE_DATA_TYP,DDL_DATA_LEN,DDL_DATA_PREC_NUM,DDL_DATA_SCALE_NUM,DDL_DATA_DFLT_TXT,COL_VIEW_NME,INFO_TYP_NME,DSPY_CAPTION_TXT)select 'RRC1',CURRENT_TIMESTAMP,'NUVEEN:CSTM','LAST_CHG_TMS','00003320','Y','TIMESTAMP(0)',6,'Last Change Date/Time','This field contains the latest date and time that the values of the table occurrence on which this field resides were changed.','DATE',0,0,0,null,'LAST_CHG_TMS','LAST_CHANGE_DATE/TIME',NULL
FROM DUAL WHERE NOT EXISTS
(SELECT 1 FROM FT_T_CLDF WHERE TBL_ID ='RRC1' AND COL_NME='LAST_CHG_TMS' );

Insert into FT_T_CLDF(TBL_ID,LAST_CHG_TMS,LAST_CHG_USR_ID,COL_NME,FLD_ID,COL_REQ_IND,DDL_DATA_TYP,COL_SQ_NUM,LOGL_NME,COL_DESC,DDL_BASE_DATA_TYP,DDL_DATA_LEN,DDL_DATA_PREC_NUM,DDL_DATA_SCALE_NUM,DDL_DATA_DFLT_TXT,COL_VIEW_NME,INFO_TYP_NME,DSPY_CAPTION_TXT)select 'RRC1',CURRENT_TIMESTAMP,'NUVEEN:CSTM','START_TMS','00007490','Y','TIMESTAMP(0)',7,'Start Date/Time','This field specifies the date and time from which the table occurrence is active.  In conjunction with the End Date/Time field, it determines the period when the table occurrence is active.','DATE',0,0,0,null,'START_TMS','DATE/TIME',NULL
FROM DUAL WHERE NOT EXISTS
(SELECT 1 FROM FT_T_CLDF WHERE TBL_ID ='RRC1' AND COL_NME='START_TMS' );

Insert into FT_T_CLDF(TBL_ID,LAST_CHG_TMS,LAST_CHG_USR_ID,COL_NME,FLD_ID,COL_REQ_IND,DDL_DATA_TYP,COL_SQ_NUM,LOGL_NME,COL_DESC,DDL_BASE_DATA_TYP,DDL_DATA_LEN,DDL_DATA_PREC_NUM,DDL_DATA_SCALE_NUM,DDL_DATA_DFLT_TXT,COL_VIEW_NME,INFO_TYP_NME,DSPY_CAPTION_TXT)select 'RRC1',CURRENT_TIMESTAMP,'NUVEEN:CSTM','END_TMS','00007450','N','TIMESTAMP(0)',8,'End Date/Time','This field specifies the date and time after which the table occurrence is no longer active.  A value of "null" in this field indicates that an End Date/Time is not given and that the table occurrence is active.  The End Date/Time is used in conjunction with the Start Date/Time to determine the period when the table occurrence is active.','DATE',0,0,0,null,'END_TMS','DATE/TIME',NULL
FROM DUAL WHERE NOT EXISTS
(SELECT 1 FROM FT_T_CLDF WHERE TBL_ID ='RRC1' AND COL_NME='END_TMS' );

Insert into FT_T_CLDF(TBL_ID,LAST_CHG_TMS,LAST_CHG_USR_ID,COL_NME,FLD_ID,COL_REQ_IND,DDL_DATA_TYP,COL_SQ_NUM,LOGL_NME,COL_DESC,DDL_BASE_DATA_TYP,DDL_DATA_LEN,DDL_DATA_PREC_NUM,DDL_DATA_SCALE_NUM,DDL_DATA_DFLT_TXT,COL_VIEW_NME,INFO_TYP_NME,DSPY_CAPTION_TXT)select 'RRC1',CURRENT_TIMESTAMP,'NUVEEN:CSTM','LAST_CHG_USR_ID','00003325','Y','VARCHAR(256)',9,'Last Change User ID','This field contains the identifier of the last person or application that changed the values of the table occurrence on which this field resides.','VARCHAR',256,0,0,null,'LAST_CHG_USR_ID','USER_IDENTIFIER',NULL
FROM DUAL WHERE NOT EXISTS
(SELECT 1 FROM FT_T_CLDF WHERE TBL_ID ='RRC1' AND COL_NME='LAST_CHG_USR_ID' );
