INSERT INTO FT_T_RTNG (RTNG_SET_OID, RTNG_SET_TBL_TYP, RTNG_SET_MNEM, LAST_CHG_TMS, LAST_CHG_USR_ID, START_TMS, RTNG_SET_NME, RTNG_SET_DESC, DATA_STAT_TYP, DATA_SRC_ID, RTNG_TENOR_MNEM)
SELECT 'NSRTNG0001', 'ALL', 'NWQRTNG', SYSDATE(), 'NUVEEN:CSTM', SYSDATE(), 'NWQPMRating', 'NWQPMRating', 'ACTIVE', NULL, 'LT' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM FT_T_RTNG WHERE RTNG_SET_MNEM = 'NWQRTNG');

----BB AMBEST ratings

INSERT INTO FT_T_RTNG (RTNG_SET_OID, RTNG_SET_TBL_TYP, RTNG_SET_MNEM, LAST_CHG_TMS, LAST_CHG_USR_ID, START_TMS, RTNG_SET_NME, RTNG_SET_DESC, DATA_STAT_TYP, DATA_SRC_ID, RTNG_TENOR_MNEM)
SELECT 'BBAMBEST01', 'ISSU', 'BBAMBEST', SYSDATE(), 'NUVEEN:CSTM', SYSDATE(), 'A.M. Best Rating', 'A.M. Best Rating', 'ACTIVE', 'BB', 'MIXED' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM FT_T_RTNG WHERE RTNG_SET_MNEM = 'BBAMBEST');

-- Moodys Mixed Rating
INSERT INTO FT_T_RTNG (RTNG_SET_OID, RTNG_SET_TBL_TYP, RTNG_SET_MNEM, LAST_CHG_TMS, LAST_CHG_USR_ID, START_TMS, RTNG_SET_NME, RTNG_SET_DESC, DATA_STAT_TYP, DATA_SRC_ID, RTNG_TENOR_MNEM)
SELECT 'BBMXDMDY01', 'ISSU', 'BBMXDMDY', SYSDATE(), 'NUVEEN:CSTM', SYSDATE(), 'BB Moodys Mixed Rating', 'BB Moodys Mixed Rating', 'ACTIVE', 'BB', 'MIXED' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM FT_T_RTNG WHERE RTNG_SET_MNEM = 'BBMXDMDY');

-- SP Mixed Rating
INSERT INTO FT_T_RTNG (RTNG_SET_OID, RTNG_SET_TBL_TYP, RTNG_SET_MNEM, LAST_CHG_TMS, LAST_CHG_USR_ID, START_TMS, RTNG_SET_NME, RTNG_SET_DESC, DATA_STAT_TYP, DATA_SRC_ID, RTNG_TENOR_MNEM)
SELECT 'BBMXDSP01', 'ISSU', 'BBMXDSP', SYSDATE(), 'NUVEEN:CSTM', SYSDATE(), 'BB SNP Mixed Rating', 'BB SNP Mixed Rating', 'ACTIVE', 'BB', 'MIXED' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM FT_T_RTNG WHERE RTNG_SET_MNEM = 'BBMXDSP');

-- Fitch Mixed Rating
INSERT INTO FT_T_RTNG (RTNG_SET_OID, RTNG_SET_TBL_TYP, RTNG_SET_MNEM, LAST_CHG_TMS, LAST_CHG_USR_ID, START_TMS, RTNG_SET_NME, RTNG_SET_DESC, DATA_STAT_TYP, DATA_SRC_ID, RTNG_TENOR_MNEM)
SELECT 'BBMXDFT01', 'ISSU', 'BBMXDFT', SYSDATE(), 'NUVEEN:CSTM', SYSDATE(), 'BB Fitch Mixed Rating', 'BB Fitch Mixed Rating', 'ACTIVE', 'BB', 'MIXED' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM FT_T_RTNG WHERE RTNG_SET_MNEM = 'BBMXDFT');

--added C-Scope ratings into the common sql here
-- Revised the rtng_set_oid to avoid duplication with existing oids.
INSERT INTO ft_t_rtng (rtng_set_oid,rtng_set_tbl_typ,rtng_set_mnem,rtng_tenor_mnem,rtng_set_curr_cde,start_tms,end_tms,last_chg_tms,last_chg_usr_id,rtng_set_typ,rtng_set_nme,rtng_set_desc,data_stat_typ,data_src_id,inst_mnem,finsrl_typ,gu_id,gu_typ,gu_cnt,rtng_set_scale_typ,finr_oid,gunt_oid) select 'NUVCS00001','ALL','CsMOODYS','LT',NULL,SYSDATE(),NULL,SYSDATE(),'NUVEEN:CSTM',NULL,'Cscope_MOODYS','Cscope_MOODYS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_rtng WHERE rtng_set_mnem = 'CsMOODYS');
INSERT INTO ft_t_rtng (rtng_set_oid,rtng_set_tbl_typ,rtng_set_mnem,rtng_tenor_mnem,rtng_set_curr_cde,start_tms,end_tms,last_chg_tms,last_chg_usr_id,rtng_set_typ,rtng_set_nme,rtng_set_desc,data_stat_typ,data_src_id,inst_mnem,finsrl_typ,gu_id,gu_typ,gu_cnt,rtng_set_scale_typ,finr_oid,gunt_oid) select 'NUVCS00002','ALL','CsSnP','LT',NULL,SYSDATE(),NULL,SYSDATE(),'NUVEEN:CSTM',NULL,'Cscope_S&P','Cscope_S&P',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_rtng WHERE rtng_set_mnem = 'CsSnP');
INSERT INTO ft_t_rtng (rtng_set_oid,rtng_set_tbl_typ,rtng_set_mnem,rtng_tenor_mnem,rtng_set_curr_cde,start_tms,end_tms,last_chg_tms,last_chg_usr_id,rtng_set_typ,rtng_set_nme,rtng_set_desc,data_stat_typ,data_src_id,inst_mnem,finsrl_typ,gu_id,gu_typ,gu_cnt,rtng_set_scale_typ,finr_oid,gunt_oid) select 'NUVCS00003','ALL','CsJNRtng','LT',NULL,SYSDATE(),NULL,SYSDATE(),'NUVEEN:CSTM',NULL,'Cscope_JNRtng','Cscope_JNRtng',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_rtng WHERE rtng_set_mnem = 'CsJNRtng');
INSERT INTO ft_t_rtng (rtng_set_oid,rtng_set_tbl_typ,rtng_set_mnem,rtng_tenor_mnem,rtng_set_curr_cde,start_tms,end_tms,last_chg_tms,last_chg_usr_id,rtng_set_typ,rtng_set_nme,rtng_set_desc,data_stat_typ,data_src_id,inst_mnem,finsrl_typ,gu_id,gu_typ,gu_cnt,rtng_set_scale_typ,finr_oid,gunt_oid) select 'NUVCS00004','ALL','CsFITCH','LT',NULL,SYSDATE(),NULL,SYSDATE(),'NUVEEN:CSTM',NULL,'Cscope_FITCH','Cscope_FITCH',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_rtng WHERE rtng_set_mnem = 'CsFITCH');


--SP recovery ratings

INSERT INTO FT_T_RTNG (RTNG_SET_OID, RTNG_SET_TBL_TYP, RTNG_SET_MNEM, LAST_CHG_TMS, LAST_CHG_USR_ID, START_TMS, RTNG_SET_NME, RTNG_SET_DESC, DATA_STAT_TYP, DATA_SRC_ID, RTNG_TENOR_MNEM)
SELECT 'U8yzn>2RW1', 'ISSU', 'ISSRCRTG', SYSDATE(), 'NUVEEN:CSTM', SYSDATE(), 'SP Issue Recovery Rating', 'SP Issue Recovery Rating', 'ACTIVE', 'BB', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM FT_T_RTNG WHERE RTNG_SET_MNEM = 'ISSRCRTG');

--RTNG updates for Issuers to align with Eagle details to be published

-- rtng_set_nme   -- srcIntfcInst publishing field 
update ft_t_rtng set rtng_set_nme = 'BL-DBRS-ST RTG', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'DBSTISSR' and data_src_id = 'BB'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'BL-DBRS-ST RTG' and rtng_set_mnem = 'DBSTISSR' and data_src_id = 'BB') ;
update ft_t_rtng set rtng_set_nme = 'BL-FCH-LT RTG', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'FTLTISSR' and data_src_id = 'BB'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'BL-FCH-LT RTG' and rtng_set_mnem = 'FTLTISSR' and data_src_id = 'BB') ;
update ft_t_rtng set rtng_set_nme = 'BL-FCH-LT-DF RT', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'FTLTIRDF' and data_src_id = 'BB'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'BL-FCH-LT-DF RT' and rtng_set_mnem = 'FTLTIRDF' and data_src_id = 'BB') ;
update ft_t_rtng set rtng_set_nme = 'BL-FCH-LT-FC RT', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'CRFTLTFC' and data_src_id = 'BB'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'BL-FCH-LT-FC RT' and rtng_set_mnem = 'CRFTLTFC' and data_src_id = 'BB') ;
update ft_t_rtng set rtng_set_nme = 'BL-FCH-LT-LC RT', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'FTLTLCDB' and data_src_id = 'BB'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'BL-FCH-LT-LC RT' and rtng_set_mnem = 'FTLTLCDB' and data_src_id = 'BB') ;
update ft_t_rtng set rtng_set_nme = 'BL-FCH-MM RTG', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'MMFTSTRT' and data_src_id = 'BB'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'BL-FCH-MM RTG' and rtng_set_mnem = 'MMFTSTRT' and data_src_id = 'BB') ;
update ft_t_rtng set rtng_set_nme = 'BL-FCH-SRUNSDBT', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'CRFTSRUS' and data_src_id = 'BB'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'BL-FCH-SRUNSDBT' and rtng_set_mnem = 'CRFTSRUS' and data_src_id = 'BB') ;
update ft_t_rtng set rtng_set_nme = 'BL-FCH-ST RTG', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'FTSTISSR' and data_src_id = 'BB'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'BL-FCH-ST RTG' and rtng_set_mnem = 'FTSTISSR' and data_src_id = 'BB') ;
update ft_t_rtng set rtng_set_nme = 'BL-MDY-LT RTG', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'MDYISRRT' and data_src_id = 'BB'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'BL-MDY-LT RTG' and rtng_set_mnem = 'MDYISRRT' and data_src_id = 'BB') ;
update ft_t_rtng set rtng_set_nme = 'BL-MDY-LT-FC RT', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'MDLTFCDR' and data_src_id = 'BB'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'BL-MDY-LT-FC RT' and rtng_set_mnem = 'MDLTFCDR' and data_src_id = 'BB') ;
update ft_t_rtng set rtng_set_nme = 'BL-MDY-LT-LC RT', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'MDLTLCDR' and data_src_id = 'BB'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'BL-MDY-LT-LC RT' and rtng_set_mnem = 'MDLTLCDR' and data_src_id = 'BB') ;
update ft_t_rtng set rtng_set_nme = 'BL-MDY-MM RTG', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'MMSTMDRT' and data_src_id = 'BB'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'BL-MDY-MM RTG' and rtng_set_mnem = 'MMSTMDRT' and data_src_id = 'BB') ;
update ft_t_rtng set rtng_set_nme = 'BL-MDY-PFD RTG', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'MDYPFDRT' and data_src_id = 'BB'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'BL-MDY-PFD RTG' and rtng_set_mnem = 'MDYPFDRT' and data_src_id = 'BB') ;
update ft_t_rtng set rtng_set_nme = 'BL-MDY-SRUNSDBT', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'MDYUNSRT' and data_src_id = 'BB'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'BL-MDY-SRUNSDBT' and rtng_set_mnem = 'MDYUNSRT' and data_src_id = 'BB') ;
update ft_t_rtng set rtng_set_nme = 'BL-MDY-STDBT', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'MDSTDEBT' and data_src_id = 'BB'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'BL-MDY-STDBT' and rtng_set_mnem = 'MDSTDEBT' and data_src_id = 'BB') ;
update ft_t_rtng set rtng_set_nme = 'BL-MDY-SUB-DEBT', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'MDYSUBRT' and data_src_id = 'BB'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'BL-MDY-SUB-DEBT' and rtng_set_mnem = 'MDYSUBRT' and data_src_id = 'BB') ;
update ft_t_rtng set rtng_set_nme = 'BL-SP-LT-FC RTG', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'SPLTFCIC' and data_src_id = 'BB'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'BL-SP-LT-FC RTG' and rtng_set_mnem = 'SPLTFCIC' and data_src_id = 'BB') ;
update ft_t_rtng set rtng_set_nme = 'BL-SP-LT-LC RTG', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'SPLTLCIC' and data_src_id = 'BB'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'BL-SP-LT-LC RTG' and rtng_set_mnem = 'SPLTLCIC' and data_src_id = 'BB') ;
update ft_t_rtng set rtng_set_nme = 'BL-SP-MM RTG', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'MMSPSTRT' and data_src_id = 'BB'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'BL-SP-MM RTG' and rtng_set_mnem = 'MMSPSTRT' and data_src_id = 'BB') ;
update ft_t_rtng set rtng_set_nme = 'BL-SP-ST-FC RTG', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'SPSTFICR' and data_src_id = 'BB'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'BL-SP-ST-FC RTG' and rtng_set_mnem = 'SPSTFICR' and data_src_id = 'BB') ;
update ft_t_rtng set rtng_set_nme = 'BL-SP-ST-LC RTG', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'SPSTLICR' and data_src_id = 'BB'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'BL-SP-ST-LC RTG' and rtng_set_mnem = 'SPSTLICR' and data_src_id = 'BB') ;
update ft_t_rtng set rtng_set_nme = 'CRS-FCH-RTG', LAST_CHG_TMS = now(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'CsFITCH'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'CRS-FCH-RTG' and rtng_set_mnem = 'CsFITCH' ) ;
update ft_t_rtng set rtng_set_nme = 'CRS-JNC-RTG', LAST_CHG_TMS = now(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'CsJNRtng'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'CRS-JNC-RTG' and rtng_set_mnem = 'CsJNRtng' ) ;
update ft_t_rtng set rtng_set_nme = 'CRS-MDY-RTG', LAST_CHG_TMS = now(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'CsMOODYS'   and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'CRS-MDY-RTG' and rtng_set_mnem = 'CsMOODYS') ;
update ft_t_rtng set rtng_set_nme = 'CRS-SP-RTG', LAST_CHG_TMS = now(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'CsSnP'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'CRS-SP-RTG' and rtng_set_mnem = 'CsSnP' ) ;

--RTNG_TENOR_MNEM    -- ratingTypeInd publishing field
update ft_t_rtng set RTNG_TENOR_MNEM = 'ST', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'DBSTISSR' and RTNG_SET_NME ='BL-DBRS-ST RTG'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'ST' and rtng_set_mnem = 'DBSTISSR' and RTNG_SET_NME ='BL-DBRS-ST RTG' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'LT', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'FTLTISSR' and RTNG_SET_NME ='BL-FCH-LT RTG'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'LT' and rtng_set_mnem = 'FTLTISSR' and RTNG_SET_NME ='BL-FCH-LT RTG' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'LT_DF', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'FTLTIRDF' and RTNG_SET_NME ='BL-FCH-LT-DF RT'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'LT_DF' and rtng_set_mnem = 'FTLTIRDF' and RTNG_SET_NME ='BL-FCH-LT-DF RT' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'LT_FC', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'CRFTLTFC' and RTNG_SET_NME ='BL-FCH-LT-FC RT'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'LT_FC' and rtng_set_mnem = 'CRFTLTFC' and RTNG_SET_NME ='BL-FCH-LT-FC RT' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'LT_LC', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'FTLTLCDB' and RTNG_SET_NME ='BL-FCH-LT-LC RT'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'LT_LC' and rtng_set_mnem = 'FTLTLCDB' and RTNG_SET_NME ='BL-FCH-LT-LC RT' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'ST', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'MMFTSTRT' and RTNG_SET_NME ='BL-FCH-MM RTG'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'ST' and rtng_set_mnem = 'MMFTSTRT' and RTNG_SET_NME ='BL-FCH-MM RTG' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'SRUNS_DB', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'CRFTSRUS' and RTNG_SET_NME ='BL-FCH-SRUNSDBT'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'SRUNS_DB' and rtng_set_mnem = 'CRFTSRUS' and RTNG_SET_NME ='BL-FCH-SRUNSDBT' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'ST', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'FTSTISSR' and RTNG_SET_NME ='BL-FCH-ST RTG'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'ST' and rtng_set_mnem = 'FTSTISSR' and RTNG_SET_NME ='BL-FCH-ST RTG' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'LT', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'MDYISRRT' and RTNG_SET_NME ='BL-MDY-LT RTG'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'LT' and rtng_set_mnem = 'MDYISRRT' and RTNG_SET_NME ='BL-MDY-LT RTG' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'LT_FC', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'MDLTFCDR' and RTNG_SET_NME ='BL-MDY-LT-FC RT'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'LT_FC' and rtng_set_mnem = 'MDLTFCDR' and RTNG_SET_NME ='BL-MDY-LT-FC RT' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'LT_LC', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'MDLTLCDR' and RTNG_SET_NME ='BL-MDY-LT-LC RT'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'LT_LC' and rtng_set_mnem = 'MDLTLCDR' and RTNG_SET_NME ='BL-MDY-LT-LC RT' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'ST', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'MMSTMDRT' and RTNG_SET_NME ='BL-MDY-MM RTG'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'ST' and rtng_set_mnem = 'MMSTMDRT' and RTNG_SET_NME ='BL-MDY-MM RTG' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'PFD', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'MDYPFDRT' and RTNG_SET_NME ='BL-MDY-PFD RTG'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'PFD' and rtng_set_mnem = 'MDYPFDRT' and RTNG_SET_NME ='BL-MDY-PFD RTG' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'SRUNS_DB', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'MDYUNSRT' and RTNG_SET_NME ='BL-MDY-SRUNSDBT'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'SRUNS_DB' and rtng_set_mnem = 'MDYUNSRT' and RTNG_SET_NME ='BL-MDY-SRUNSDBT' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'ST', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'MDSTDEBT' and RTNG_SET_NME ='BL-MDY-STDBT'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'ST' and rtng_set_mnem = 'MDSTDEBT' and RTNG_SET_NME ='BL-MDY-STDBT' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'SUB_DEBT', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'MDYSUBRT' and RTNG_SET_NME ='BL-MDY-SUB-DEBT'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'SUB_DEBT' and rtng_set_mnem = 'MDYSUBRT' and RTNG_SET_NME ='BL-MDY-SUB-DEBT' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'LT_FC', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'SPLTFCIC' and RTNG_SET_NME ='BL-SP-LT-FC RTG'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'LT_FC' and rtng_set_mnem = 'SPLTFCIC' and RTNG_SET_NME ='BL-SP-LT-FC RTG' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'LT_LC', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'SPLTLCIC' and RTNG_SET_NME ='BL-SP-LT-LC RTG'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'LT_LC' and rtng_set_mnem = 'SPLTLCIC' and RTNG_SET_NME ='BL-SP-LT-LC RTG' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'ST', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'MMSPSTRT' and RTNG_SET_NME ='BL-SP-MM RTG'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'ST' and rtng_set_mnem = 'MMSPSTRT' and RTNG_SET_NME ='BL-SP-MM RTG' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'ST_FC', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'SPSTFICR' and RTNG_SET_NME ='BL-SP-ST-FC RTG'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'ST_FC' and rtng_set_mnem = 'SPSTFICR' and RTNG_SET_NME ='BL-SP-ST-FC RTG' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'ST_LC', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'SPSTLICR' and RTNG_SET_NME ='BL-SP-ST-LC RTG'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'ST_LC' and rtng_set_mnem = 'SPSTLICR' and RTNG_SET_NME ='BL-SP-ST-LC RTG' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'LT', LAST_CHG_TMS = now(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'CsFITCH' and RTNG_SET_NME ='CRS-FCH-RTG'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'LT' and rtng_set_mnem = 'CsFITCH' and RTNG_SET_NME ='CRS-FCH-RTG' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'LT', LAST_CHG_TMS = now(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'CsJNRtng' and RTNG_SET_NME ='CRS-JNC-RTG'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'LT' and rtng_set_mnem = 'CsJNRtng' and RTNG_SET_NME ='CRS-JNC-RTG' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'LT', LAST_CHG_TMS = now(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'CsMOODYS' and RTNG_SET_NME ='CRS-MDY-RTG'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'LT' and rtng_set_mnem = 'CsMOODYS' and RTNG_SET_NME ='CRS-MDY-RTG' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'LT', LAST_CHG_TMS = now(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'CsSnP' and RTNG_SET_NME ='CRS-SP-RTG'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'LT' and rtng_set_mnem = 'CsSnP' and RTNG_SET_NME ='CRS-SP-RTG' );



-- inst_mnem -- provider publishing field
update ft_t_rtng set inst_mnem = 'MOODYS', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE END_TMS IS NULL AND INST_MNEM ='MOODYS RDS';
update ft_t_rtng set inst_mnem = 'SP', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE END_TMS IS NULL AND INST_MNEM ='S&P';

--RTNG updates for Instruments to align with Eagle details to be published
-- rtng_set_nme  -- srcIntfcInst publishing field 
update ft_t_rtng set rtng_set_nme = 'BL_BL_COMP RTG', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'BBCMPSTE' and data_src_id = 'BB'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'BL_BL_COMP RTG' and rtng_set_mnem = 'BBCMPSTE' and data_src_id = 'BB') ;
update ft_t_rtng set rtng_set_nme = 'BL-DBRS RTG', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'DOMINION' and data_src_id = 'BB'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'BL-DBRS RTG' and rtng_set_mnem = 'DOMINION' and data_src_id = 'BB') ;
update ft_t_rtng set rtng_set_nme = 'BL-FCH-LT RTG', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'LTISSURT' and data_src_id = 'BB'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'BL-FCH-LT RTG' and rtng_set_mnem = 'LTISSURT' and data_src_id = 'BB') ;
update ft_t_rtng set rtng_set_nme = 'BL-FCH-LT-UN RT', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'LTISRDRF' and data_src_id = 'BB'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'BL-FCH-LT-UN RT' and rtng_set_mnem = 'LTISRDRF' and data_src_id = 'BB') ;
update ft_t_rtng set rtng_set_nme = 'BL-FCH-ST RTG', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'STISSURT' and data_src_id = 'BB'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'BL-FCH-ST RTG' and rtng_set_mnem = 'STISSURT' and data_src_id = 'BB') ;
update ft_t_rtng set rtng_set_nme = 'BL-MDY-LT RTG', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = '534' and data_src_id = 'BB'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'BL-MDY-LT RTG' and rtng_set_mnem = '534' and data_src_id = 'BB') ;
update ft_t_rtng set rtng_set_nme = 'BL-MDY-LT-UN RT', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'MDYLTURT' and data_src_id = 'BB'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'BL-MDY-LT-UN RT' and rtng_set_mnem = 'MDYLTURT' and data_src_id = 'BB') ;
update ft_t_rtng set rtng_set_nme = 'BL-MDY-ST RTG', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = '535' and data_src_id = 'BB'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'BL-MDY-ST RTG' and rtng_set_mnem = '535' and data_src_id = 'BB') ;
update ft_t_rtng set rtng_set_nme = 'BL-SP-LT RTG', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'SPLTISET' and data_src_id = 'BB'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'BL-SP-LT RTG' and rtng_set_mnem = 'SPLTISET' and data_src_id = 'BB') ;
update ft_t_rtng set rtng_set_nme = 'BL-SP-LT-UN RTG', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'SPUNDLYG' and data_src_id = 'BB'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'BL-SP-LT-UN RTG' and rtng_set_mnem = 'SPUNDLYG' and data_src_id = 'BB') ;
update ft_t_rtng set rtng_set_nme = 'BL-SP-ST RTG', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'SPSHISET' and data_src_id = 'BB'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'BL-SP-ST RTG' and rtng_set_mnem = 'SPSHISET' and data_src_id = 'BB') ;
update ft_t_rtng set rtng_set_nme = 'BL-AMBEST-RTG', LAST_CHG_TMS = now(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'BBAMBEST' and data_src_id = 'BB'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'BL-AMBEST-RTG' and rtng_set_mnem = 'BBAMBEST' and data_src_id = 'BB') ;
update ft_t_rtng set rtng_set_nme = 'BL-SP RTG', LAST_CHG_TMS = now(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'BBMXDSP' and data_src_id = 'BB'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'BL-SP RTG' and rtng_set_mnem = 'BBMXDSP' and data_src_id = 'BB') ;
update ft_t_rtng set rtng_set_nme = 'BL-FCH RTG', LAST_CHG_TMS = now(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'BBMXDFT' and data_src_id = 'BB'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'BL-FCH RTG' and rtng_set_mnem = 'BBMXDFT' and data_src_id = 'BB') ;
update ft_t_rtng set rtng_set_nme = 'BL-MDY RTG', LAST_CHG_TMS = now(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'BBMXDMDY' and data_src_id = 'BB'  and not exists (select 1 from ft_t_rtng where end_tms is null and rtng_set_nme = 'BL-MDY RTG' and rtng_set_mnem = 'BBMXDMDY' and data_src_id = 'BB') ;


-- RTNG_TENOR_MNEM -- ratingTypeInd publishing field
update ft_t_rtng set RTNG_TENOR_MNEM = 'COMP', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'BBCMPSTE' and RTNG_SET_NME ='BL_BL_COMP RTG'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'COMP' and rtng_set_mnem = 'BBCMPSTE' and RTNG_SET_NME ='BL_BL_COMP RTG' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'MIXED', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'DOMINION' and RTNG_SET_NME ='BL-DBRS RTG'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'MIXED' and rtng_set_mnem = 'DOMINION' and RTNG_SET_NME ='BL-DBRS RTG' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'LT', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'LTISSURT' and RTNG_SET_NME ='BL-FCH-LT RTG'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'LT' and rtng_set_mnem = 'LTISSURT' and RTNG_SET_NME ='BL-FCH-LT RTG' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'LTMUUNDL', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'LTISRDRF' and RTNG_SET_NME ='BL-FCH-LT-UN RT'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'LTMUUNDL' and rtng_set_mnem = 'LTISRDRF' and RTNG_SET_NME ='BL-FCH-LT-UN RT' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'ST', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'STISSURT' and RTNG_SET_NME ='BL-FCH-ST RTG'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'ST' and rtng_set_mnem = 'STISSURT' and RTNG_SET_NME ='BL-FCH-ST RTG' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'LT', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = '534' and RTNG_SET_NME ='BL-MDY-LT RTG'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'LT' and rtng_set_mnem = '534' and RTNG_SET_NME ='BL-MDY-LT RTG' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'LT_MU_UN', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'MDYLTURT' and RTNG_SET_NME ='BL-MDY-LT-UN RT'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'LT_MU_UN' and rtng_set_mnem = 'MDYLTURT' and RTNG_SET_NME ='BL-MDY-LT-UN RT' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'ST', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = '535' and RTNG_SET_NME ='BL-MDY-ST RTG'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'ST' and rtng_set_mnem = '535' and RTNG_SET_NME ='BL-MDY-ST RTG' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'LT', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'SPLTISET' and RTNG_SET_NME ='BL-SP-LT RTG'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'LT' and rtng_set_mnem = 'SPLTISET' and RTNG_SET_NME ='BL-SP-LT RTG' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'LT_MU_UN', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'SPUNDLYG' and RTNG_SET_NME ='BL-SP-LT-UN RTG'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'LT_MU_UN' and rtng_set_mnem = 'SPUNDLYG' and RTNG_SET_NME ='BL-SP-LT-UN RTG' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'ST', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'SPSHISET' and RTNG_SET_NME ='BL-SP-ST RTG'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'ST' and rtng_set_mnem = 'SPSHISET' and RTNG_SET_NME ='BL-SP-ST RTG' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'MIXED', LAST_CHG_TMS = now(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'BBAMBEST' and RTNG_SET_NME ='BL-AMBEST-RTG'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'MIXED' and rtng_set_mnem = 'BBAMBEST' and RTNG_SET_NME ='BL-AMBEST-RTG' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'MIXED', LAST_CHG_TMS = now(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'BBMXDSP' and RTNG_SET_NME ='BL-SP RTG'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'MIXED' and rtng_set_mnem = 'BBMXDSP' and RTNG_SET_NME ='BL-SP RTG' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'MIXED', LAST_CHG_TMS = now(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'BBMXDFT' and RTNG_SET_NME ='BL-FCH RTG'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'MIXED' and rtng_set_mnem = 'BBMXDFT' and RTNG_SET_NME ='BL-FCH RTG' );
update ft_t_rtng set RTNG_TENOR_MNEM = 'MIXED', LAST_CHG_TMS = now(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'BBMXDMDY' and RTNG_SET_NME ='BL-MDY RTG'and not exists(select 1 from ft_t_rtng where end_tms is null and  RTNG_TENOR_MNEM = 'MIXED' and rtng_set_mnem = 'BBMXDMDY' and RTNG_SET_NME ='BL-MDY RTG' );

-- inst_mnem -- provider publishing field
update ft_t_rtng set inst_mnem = 'BLOOMBERG', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE END_TMS IS NULL AND RTNG_SET_MNEM ='BBCMPSTE'
and not exists (select 1 from ft_t_rtng where inst_mnem = 'BLOOMBERG' and end_tms is null and RTNG_SET_MNEM ='BBCMPSTE' );
update ft_t_rtng set inst_mnem = 'MOODYS', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE END_TMS IS NULL AND INST_MNEM ='MOODYS RDS';
update ft_t_rtng set inst_mnem = 'SP', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE END_TMS IS NULL AND INST_MNEM ='S&P';

-- for custom FIRT mapping of money market ratings
update ft_t_rtng set rtng_set_tbl_typ = 'ALL', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'MMFTSTRT' ;
update ft_t_rtng set rtng_set_tbl_typ = 'ALL', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'MMSTMDRT' ;
update ft_t_rtng set rtng_set_tbl_typ = 'ALL', LAST_CHG_TMS = SYSDATE(), last_chg_usr_id = 'NUVEEN:CSTM' WHERE end_tms is null and rtng_set_mnem = 'MMSPSTRT' ;

-- Credit Scope

INSERT INTO ft_t_rtng (rtng_set_oid, rtng_set_tbl_typ, rtng_set_mnem, rtng_tenor_mnem, start_tms, last_chg_tms, last_chg_usr_id, rtng_set_nme, rtng_set_desc)  
  SELECT new_oid(), 'ALL', 'JNUVEEN', 'LT', SYSDATE(), SYSDATE(), 'NUVEEN:CSTM', 'Jnuveen Rating', 'Jnuveen Rating Set'
    FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_rtng WHERE rtng_set_mnem = 'JNUVEEN' AND end_tms IS NULL);

INSERT INTO ft_t_rtng (rtng_set_oid, rtng_set_tbl_typ, rtng_set_mnem, rtng_tenor_mnem, start_tms, last_chg_tms, last_chg_usr_id, rtng_set_nme, rtng_set_desc)  
  SELECT new_oid(), 'ALL', 'CRSSNP', 'LT', SYSDATE(), SYSDATE(), 'NUVEEN:CSTM', 'CreditScope SnP Rolled-up Rating', 'CreditScope SnP Rolled-up Rating Set'
    FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_rtng WHERE rtng_set_mnem = 'CRSSNP' AND end_tms IS NULL);

INSERT INTO ft_t_rtng (rtng_set_oid, rtng_set_tbl_typ, rtng_set_mnem, rtng_tenor_mnem, start_tms, last_chg_tms, last_chg_usr_id, rtng_set_nme, rtng_set_desc)  
  SELECT new_oid(), 'ALL', 'CRSMDY', 'LT', SYSDATE(), SYSDATE(), 'NUVEEN:CSTM', 'CreditScope Moodys Rolled-up Rating', 'CreditScope Moodys Rolled-up Rating Set'
    FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_rtng WHERE rtng_set_mnem = 'CRSMDY' AND end_tms IS NULL);

INSERT INTO ft_t_rtng (rtng_set_oid, rtng_set_tbl_typ, rtng_set_mnem, rtng_tenor_mnem, start_tms, last_chg_tms, last_chg_usr_id, rtng_set_nme, rtng_set_desc)  
  SELECT new_oid(), 'ALL', 'CRSFTCH', 'LT', SYSDATE(), SYSDATE(), 'NUVEEN:CSTM', 'CreditScope Fitch Rolled-up Rating', 'CreditScope Fitch Rolled-up Rating Set'
    FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_rtng WHERE rtng_set_mnem = 'CRSFTCH' AND end_tms IS NULL);

-- TLNSM-518: Moody's underlying ratings
INSERT INTO ft_t_rtng (rtng_set_oid,rtng_set_tbl_typ,rtng_set_mnem,rtng_tenor_mnem,rtng_set_curr_cde,start_tms,end_tms,last_chg_tms,last_chg_usr_id,rtng_set_typ,rtng_set_nme,rtng_set_desc,data_stat_typ,data_src_id,inst_mnem,finsrl_typ,gu_id,gu_typ,gu_cnt,rtng_set_scale_typ,finr_oid,gunt_oid) SELECT 'NSRTNG0002','ISSU','534U','LT',NULL,sysdate(),NULL,sysdate(),'NUVEEN:CSTM','RATING','Underlying Long-Term Debt Rating','LT','ACTIVE','MOODYS_RDS','MOODYS RDS','RTAGENCY',NULL,NULL,NULL,'GLOBAL',NULL,NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM FT_T_RTNG WHERE RTNG_SET_MNEM = '534U' and end_tms is null);
INSERT INTO ft_t_rtng (rtng_set_oid,rtng_set_tbl_typ,rtng_set_mnem,rtng_tenor_mnem,rtng_set_curr_cde,start_tms,end_tms,last_chg_tms,last_chg_usr_id,rtng_set_typ,rtng_set_nme,rtng_set_desc,data_stat_typ,data_src_id,inst_mnem,finsrl_typ,gu_id,gu_typ,gu_cnt,rtng_set_scale_typ,finr_oid,gunt_oid) SELECT 'NSRTNG0003','ISSU','535U','ST',NULL,sysdate(),NULL,sysdate(),'NUVEEN:CSTM','RATING','Underlying Short-Term Debt Rating','ST','ACTIVE','MOODYS_RDS','MOODYS RDS','RTAGENCY',NULL,NULL,NULL,'GLOBAL',NULL,NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM FT_T_RTNG WHERE RTNG_SET_MNEM = '535U' and end_tms is null);
INSERT INTO ft_t_rtng (rtng_set_oid,rtng_set_tbl_typ,rtng_set_mnem,rtng_tenor_mnem,rtng_set_curr_cde,start_tms,end_tms,last_chg_tms,last_chg_usr_id,rtng_set_typ,rtng_set_nme,rtng_set_desc,data_stat_typ,data_src_id,inst_mnem,finsrl_typ,gu_id,gu_typ,gu_cnt,rtng_set_scale_typ,finr_oid,gunt_oid) SELECT 'NSRTNG0004','ISSU','534I','LT',NULL,sysdate(),NULL,sysdate(),'NUVEEN:CSTM','RATING','Insured Long-Term Debt Rating','LT','ACTIVE','MOODYS_RDS','MOODYS RDS','RTAGENCY',NULL,NULL,NULL,'GLOBAL',NULL,NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM FT_T_RTNG WHERE RTNG_SET_MNEM = '534I' and end_tms is null);
INSERT INTO ft_t_rtng (rtng_set_oid,rtng_set_tbl_typ,rtng_set_mnem,rtng_tenor_mnem,rtng_set_curr_cde,start_tms,end_tms,last_chg_tms,last_chg_usr_id,rtng_set_typ,rtng_set_nme,rtng_set_desc,data_stat_typ,data_src_id,inst_mnem,finsrl_typ,gu_id,gu_typ,gu_cnt,rtng_set_scale_typ,finr_oid,gunt_oid) SELECT 'NSRTNG0005','ISSU','534N','LT',NULL,sysdate(),NULL,sysdate(),'NUVEEN:CSTM','RATING','Nuveen Long-Term Debt Rating','LT','ACTIVE','MOODYS_RDS','MOODYS RDS','RTAGENCY',NULL,NULL,NULL,'GLOBAL',NULL,NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM FT_T_RTNG WHERE RTNG_SET_MNEM = '534N' and end_tms is null);