
INSERT INTO ft_t_srle
(srle_oid, org_id, appl_id, start_tms, end_tms, last_chg_tms, last_chg_usr_id, sec_role_nme, sec_role_desc)
select 'NVNSMUSRRL', NULL, 'SSTATION', '2023-11-23 12:00:00.000', NULL, '2023-11-24 17:41:35.000', 'user1', 'sm_users', 'sm_users' from dual 
where not exists (select 'x'from ft_t_srle where srle_oid = 'NVNSMUSRRL');

INSERT INTO ft_t_srle
(srle_oid, org_id, appl_id, start_tms, end_tms, last_chg_tms, last_chg_usr_id, sec_role_nme, sec_role_desc)
select 'NVNSMRORLE', NULL, 'SSTATION', '2023-11-23 12:00:00.000', NULL, '2023-11-24 17:42:49.000', 'user1', 'sm_readonly', 'sm_readonly'
where not exists (select 'x'from ft_t_srle where srle_oid = 'NVNSMRORLE');

-- Property Master Merge 2402024
insert into ft_t_srle (srle_oid, appl_id, org_id, start_tms, end_tms, last_chg_tms, last_chg_usr_id, sec_role_nme, sec_role_desc)select 'NRESRLERAT' as srle_oid, 'SSTATION' as appl_id, NULL as org_id, SYSDATE() as start_tms, NULL::timestamp as end_tms, SYSDATE() as last_chg_tms, 'NRE:CSTM' as last_chg_usr_id, 'pm_real_assets_technology' as sec_role_nme, 'PropM user having constraints-based access to PropM UI screens, as applicable for Real Assets Technology group.' as sec_role_desc on conflict (srle_oid) where (sec_role_nme = 'pm_real_assets_technology') do update set srle_oid = EXCLUDED.srle_oid, appl_id = EXCLUDED.appl_id, org_id = EXCLUDED.org_id, end_tms = EXCLUDED.end_tms, last_chg_tms = EXCLUDED.last_chg_tms, last_chg_usr_id = EXCLUDED.last_chg_usr_id, sec_role_desc = EXCLUDED.sec_role_desc;
insert into ft_t_srle (srle_oid, appl_id, org_id, start_tms, end_tms, last_chg_tms, last_chg_usr_id, sec_role_nme, sec_role_desc)select 'NRESRLEFOF' as srle_oid, 'SSTATION' as appl_id, NULL as org_id, SYSDATE() as start_tms, NULL::timestamp as end_tms, SYSDATE() as last_chg_tms, 'NRE:CSTM' as last_chg_usr_id, 'pm_finance_operations_fund' as sec_role_nme, 'PropM user having constraints-based access to PropM UI screens, as applicable for Finance Operations (Fund) group.' as sec_role_desc on conflict (srle_oid) where (sec_role_nme = 'pm_finance_operations_fund') do update set srle_oid = EXCLUDED.srle_oid, appl_id = EXCLUDED.appl_id, org_id = EXCLUDED.org_id, end_tms = EXCLUDED.end_tms, last_chg_tms = EXCLUDED.last_chg_tms, last_chg_usr_id = EXCLUDED.last_chg_usr_id, sec_role_desc = EXCLUDED.sec_role_desc;
insert into ft_t_srle (srle_oid, appl_id, org_id, start_tms, end_tms, last_chg_tms, last_chg_usr_id, sec_role_nme, sec_role_desc)select 'NRESRLEFOP' as srle_oid, 'SSTATION' as appl_id, NULL as org_id, SYSDATE() as start_tms, NULL::timestamp as end_tms, SYSDATE() as last_chg_tms, 'NRE:CSTM' as last_chg_usr_id, 'pm_finance_operations_property' as sec_role_nme, 'PropM user having constraints-based access to PropM UI screens, as applicable for Finance Operations (Property) group.' as sec_role_desc on conflict (srle_oid) where (sec_role_nme = 'pm_finance_operations_property') do update set srle_oid = EXCLUDED.srle_oid, appl_id = EXCLUDED.appl_id, org_id = EXCLUDED.org_id, end_tms = EXCLUDED.end_tms, last_chg_tms = EXCLUDED.last_chg_tms, last_chg_usr_id = EXCLUDED.last_chg_usr_id, sec_role_desc = EXCLUDED.sec_role_desc;
insert into ft_t_srle (srle_oid, appl_id, org_id, start_tms, end_tms, last_chg_tms, last_chg_usr_id, sec_role_nme, sec_role_desc)select 'NRESRLEGNO' as srle_oid, 'SSTATION' as appl_id, NULL as org_id, SYSDATE() as start_tms, NULL::timestamp as end_tms, SYSDATE() as last_chg_tms, 'NRE:CSTM' as last_chg_usr_id, 'pm_governance_&_operations' as sec_role_nme, 'PropM user having constraints-based access to PropM UI screens, as applicable for Governance & Operations group.' as sec_role_desc on conflict (srle_oid) where (sec_role_nme = 'pm_governance_&_operations') do update set srle_oid = EXCLUDED.srle_oid, appl_id = EXCLUDED.appl_id, org_id = EXCLUDED.org_id, end_tms = EXCLUDED.end_tms, last_chg_tms = EXCLUDED.last_chg_tms, last_chg_usr_id = EXCLUDED.last_chg_usr_id, sec_role_desc = EXCLUDED.sec_role_desc;
insert into ft_t_srle (srle_oid, appl_id, org_id, start_tms, end_tms, last_chg_tms, last_chg_usr_id, sec_role_nme, sec_role_desc)select 'NRESRLEASM' as srle_oid, 'SSTATION' as appl_id, NULL as org_id, SYSDATE() as start_tms, NULL::timestamp as end_tms, SYSDATE() as last_chg_tms, 'NRE:CSTM' as last_chg_usr_id, 'pm_asset_management' as sec_role_nme, 'PropM user having constraints-based access to PropM UI screens, as applicable for Asset Management group.' as sec_role_desc on conflict (srle_oid) where (sec_role_nme = 'pm_asset_management') do update set srle_oid = EXCLUDED.srle_oid, appl_id = EXCLUDED.appl_id, org_id = EXCLUDED.org_id, end_tms = EXCLUDED.end_tms, last_chg_tms = EXCLUDED.last_chg_tms, last_chg_usr_id = EXCLUDED.last_chg_usr_id, sec_role_desc = EXCLUDED.sec_role_desc;
insert into ft_t_srle (srle_oid, appl_id, org_id, start_tms, end_tms, last_chg_tms, last_chg_usr_id, sec_role_nme, sec_role_desc)select 'NRESRLESST' as srle_oid, 'SSTATION' as appl_id, NULL as org_id, SYSDATE() as start_tms, NULL::timestamp as end_tms, SYSDATE() as last_chg_tms, 'NRE:CSTM' as last_chg_usr_id, 'pm_sustainability' as sec_role_nme, 'PropM user having constraints-based access to PropM UI screens, as applicable for Sustainability group.' as sec_role_desc on conflict (srle_oid) where (sec_role_nme = 'pm_sustainability') do update set srle_oid = EXCLUDED.srle_oid, appl_id = EXCLUDED.appl_id, org_id = EXCLUDED.org_id, end_tms = EXCLUDED.end_tms, last_chg_tms = EXCLUDED.last_chg_tms, last_chg_usr_id = EXCLUDED.last_chg_usr_id, sec_role_desc = EXCLUDED.sec_role_desc;
insert into ft_t_srle (srle_oid, appl_id, org_id, start_tms, end_tms, last_chg_tms, last_chg_usr_id, sec_role_nme, sec_role_desc)select 'NRESRLEDGV' as srle_oid, 'SSTATION' as appl_id, NULL as org_id, SYSDATE() as start_tms, NULL::timestamp as end_tms, SYSDATE() as last_chg_tms, 'NRE:CSTM' as last_chg_usr_id, 'pm_data_governance' as sec_role_nme, 'PropM user having constraints-based access to PropM UI screens, as applicable for Data Governance group.' as sec_role_desc on conflict (srle_oid) where (sec_role_nme = 'pm_data_governance') do update set srle_oid = EXCLUDED.srle_oid, appl_id = EXCLUDED.appl_id, org_id = EXCLUDED.org_id, end_tms = EXCLUDED.end_tms, last_chg_tms = EXCLUDED.last_chg_tms, last_chg_usr_id = EXCLUDED.last_chg_usr_id, sec_role_desc = EXCLUDED.sec_role_desc;
insert into ft_t_srle (srle_oid, appl_id, org_id, start_tms, end_tms, last_chg_tms, last_chg_usr_id, sec_role_nme, sec_role_desc)select 'NRESRLEUSR' as srle_oid, 'SSTATION' as appl_id, NULL as org_id, SYSDATE() as start_tms, NULL::timestamp as end_tms, SYSDATE() as last_chg_tms, 'NRE:CSTM' as last_chg_usr_id, 'pm_users' as sec_role_nme, 'PropM user having editable access to PropM UI screens.' as sec_role_desc on conflict (srle_oid) where (sec_role_nme = 'pm_users') do update set srle_oid = EXCLUDED.srle_oid, appl_id = EXCLUDED.appl_id, org_id = EXCLUDED.org_id, end_tms = EXCLUDED.end_tms, last_chg_tms = EXCLUDED.last_chg_tms, last_chg_usr_id = EXCLUDED.last_chg_usr_id, sec_role_desc = EXCLUDED.sec_role_desc;
insert into ft_t_srle (srle_oid, appl_id, org_id, start_tms, end_tms, last_chg_tms, last_chg_usr_id, sec_role_nme, sec_role_desc)select 'NRESRLERDO' as srle_oid, 'SSTATION' as appl_id, NULL as org_id, SYSDATE() as start_tms, NULL::timestamp as end_tms, SYSDATE() as last_chg_tms, 'NRE:CSTM' as last_chg_usr_id, 'pm_readonly' as sec_role_nme, 'PropM user having readonly access to PropM UI screens.' as sec_role_desc on conflict (srle_oid) where (sec_role_nme = 'pm_readonly') do update set srle_oid = EXCLUDED.srle_oid, appl_id = EXCLUDED.appl_id, org_id = EXCLUDED.org_id, end_tms = EXCLUDED.end_tms, last_chg_tms = EXCLUDED.last_chg_tms, last_chg_usr_id = EXCLUDED.last_chg_usr_id, sec_role_desc = EXCLUDED.sec_role_desc;



