CREATE OR REPLACE VIEW ft_t_cnt1
AS  SELECT ft_e_cnt1.cnt1_oid,
    ft_e_cnt1.last_chg_usr_id,
    ft_e_cnt1.data_src_id,
    ft_e_cnt1.last_chg_tms,
    ft_e_cnt1.start_tms,
    ft_e_cnt1.end_tms,
    ft_e_cnt1.instr_id,
    ft_e_cnt1.contract_nme,
    ft_e_cnt1.is_contract_active,
    ft_e_cnt1.cntrct_glob_amt,
    ft_e_cnt1.cntrct_base_crte,
    ft_e_cnt1.cntrct_base_crte_all_in,
    ft_e_cnt1.cntrct_mat_exp_dte,
    ft_e_cnt1.cntrct_nxt_pay_dte,
    ft_e_cnt1.wso_cntrct_id,
    ft_e_cnt1.cntrct_type,
    ft_e_cnt1.cntrct_freq,
    ft_e_cnt1.wso_cntrct_notes,
    ft_e_cnt1.cntrct_accrl_basis,
    ft_e_cnt1.cntrct_mnth_cnt,
    ft_e_cnt1.spread_adj,
    ft_e_cnt1.cntrct_spread_crte,
    ft_e_cnt1.cntrct_crte_optn
   FROM ft_e_cnt1;